package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	"github.com/javicabdev/asam-backend/internal/adapters/gql/generated"
	"github.com/javicabdev/asam-backend/internal/adapters/gql/middleware"
	"github.com/javicabdev/asam-backend/internal/adapters/gql/model"
	"github.com/javicabdev/asam-backend/internal/domain/models"
	"github.com/javicabdev/asam-backend/internal/domain/services/validation"
	inputPorts "github.com/javicabdev/asam-backend/internal/ports/input"
	appErrors "github.com/javicabdev/asam-backend/pkg/errors"
)

// ID is the resolver for the id field.
func (r *cashFlowResolver) ID(ctx context.Context, obj *models.CashFlow) (string, error) {
	// Asumiendo que obj.ID es de tipo uint o uint64
	return fmt.Sprintf("%d", obj.ID), nil
}

// ID is the resolver for the id field.
func (r *familiarResolver) ID(ctx context.Context, obj *models.Familiar) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// ID is the resolver for the id field.
func (r *familyResolver) ID(ctx context.Context, obj *models.Family) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// MiembroID is the resolver for the miembro_id field.
func (r *memberResolver) MiembroID(ctx context.Context, obj *models.Member) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// NumeroSocio is the resolver for the numero_socio field.
func (r *memberResolver) NumeroSocio(ctx context.Context, obj *models.Member) (string, error) {
	return obj.MembershipNumber, nil
}

// TipoMembresia is the resolver for the tipo_membresia field.
func (r *memberResolver) TipoMembresia(ctx context.Context, obj *models.Member) (model.MembershipType, error) {
	switch obj.MembershipType {
	case models.TipoMembresiaPIndividual: // "individual"
		return model.MembershipTypeIndividual, nil
	case models.TipoMembresiaPFamiliar: // "familiar"
		return model.MembershipTypeFamily, nil
	default:
		return "",
			appErrors.NewValidationError(
				fmt.Sprintf("tipo_membresia desconocido: %s", obj.MembershipType),
				map[string]string{"tipo_membresia": "desconocido"},
			)
	}
}

// Nombre is the resolver for the nombre field.
func (r *memberResolver) Nombre(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Name, nil
}

// Apellidos is the resolver for the apellidos field.
func (r *memberResolver) Apellidos(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Surnames, nil
}

// CalleNumeroPiso is the resolver for the calle_numero_piso field.
func (r *memberResolver) CalleNumeroPiso(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Address, nil
}

// CodigoPostal is the resolver for the codigo_postal field.
func (r *memberResolver) CodigoPostal(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Postcode, nil
}

// Poblacion is the resolver for the poblacion field.
func (r *memberResolver) Poblacion(ctx context.Context, obj *models.Member) (string, error) {
	return obj.City, nil
}

// Provincia is the resolver for the provincia field.
func (r *memberResolver) Provincia(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Province, nil
}

// Pais is the resolver for the pais field.
func (r *memberResolver) Pais(ctx context.Context, obj *models.Member) (string, error) {
	return obj.Country, nil
}

// Estado is the resolver for the estado field.
func (r *memberResolver) Estado(ctx context.Context, obj *models.Member) (model.MemberStatus, error) {
	switch obj.State {
	case models.EstadoActivo: // "active"
		return model.MemberStatusActive, nil
	case models.EstadoInactivo: // "inactive"
		return model.MemberStatusInactive, nil
	default:
		return "",
			appErrors.NewValidationError(
				fmt.Sprintf("estado desconocido: %s", obj.State),
				map[string]string{"estado": "desconocido"},
			)
	}
}

// FechaAlta is the resolver for the fecha_alta field.
func (r *memberResolver) FechaAlta(ctx context.Context, obj *models.Member) (*time.Time, error) {
	return &obj.RegistrationDate, nil
}

// FechaBaja is the resolver for the fecha_baja field.
func (r *memberResolver) FechaBaja(ctx context.Context, obj *models.Member) (*time.Time, error) {
	return obj.LeavingDate, nil
}

// FechaNacimiento is the resolver for the fecha_nacimiento field.
func (r *memberResolver) FechaNacimiento(ctx context.Context, obj *models.Member) (*time.Time, error) {
	return obj.BirthDate, nil
}

// DocumentoIdentidad is the resolver for the documento_identidad field.
func (r *memberResolver) DocumentoIdentidad(ctx context.Context, obj *models.Member) (*string, error) {
	return obj.IdentityCard, nil
}

// CorreoElectronico is the resolver for the correo_electronico field.
func (r *memberResolver) CorreoElectronico(ctx context.Context, obj *models.Member) (*string, error) {
	return obj.Email, nil
}

// Profesion is the resolver for the profesion field.
func (r *memberResolver) Profesion(ctx context.Context, obj *models.Member) (*string, error) {
	return obj.Profession, nil
}

// Nacionalidad is the resolver for the nacionalidad field.
func (r *memberResolver) Nacionalidad(ctx context.Context, obj *models.Member) (*string, error) {
	return &obj.Nationality, nil
}

// Observaciones is the resolver for the observaciones field.
func (r *memberResolver) Observaciones(ctx context.Context, obj *models.Member) (*string, error) {
	return obj.Remarks, nil
}

// ID is the resolver for the id field.
func (r *membershipFeeResolver) ID(ctx context.Context, obj *models.MembershipFee) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateMember is the resolver for the createMember field.
func (r *mutationResolver) CreateMember(ctx context.Context, input model.CreateMemberInput) (*models.Member, error) {
	// Solo ADMIN puede crear miembros
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.CreateMember(ctx, input)
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, input model.UpdateMemberInput) (*models.Member, error) {
	// Solo ADMIN puede actualizar miembros
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.UpdateMember(ctx, input)
}

// DeleteMember is the resolver for the deleteMember field.
func (r *mutationResolver) DeleteMember(ctx context.Context, id string) (*model.MutationResponse, error) {
	// Solo ADMIN puede eliminar miembros
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	memberID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	err = r.memberService.DeactivateMember(ctx, memberID, nil)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, err
	}
	msg := "Member successfully deleted"
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// ChangeMemberStatus is the resolver for the changeMemberStatus field.
func (r *mutationResolver) ChangeMemberStatus(ctx context.Context, id string, status model.MemberStatus) (*models.Member, error) {
	// Solo ADMIN puede cambiar estado de miembros
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// 1) Parsear el ID a uint (o el tipo que uses internamente)
	memberID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 2) Llamar al método handleMemberStatus del sub-resolver (member_resolver.go)
	memberResolver, ok := r.Member().(*memberResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	return memberResolver.handleMemberStatus(ctx, memberID, status)
}

// CreateFamily is the resolver for the createFamily field.
func (r *mutationResolver) CreateFamily(ctx context.Context, input model.CreateFamilyInput) (*models.Family, error) {
	// Solo ADMIN puede crear familias
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// 1) Validar input (opcional, si tienes validateCreateFamilyInput)
	if input.NumeroSocio == "" {
		return nil, appErrors.NewValidationError(
			"VALIDATION_FAILED: El número de familia es obligatorio",
			map[string]string{"numeroSocio": "El número de familia es obligatorio"},
		)
	}

	familyResolver, ok := r.Family().(*familyResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}

	if err := familyResolver.validateCreateFamilyInput(&input); err != nil {
		return nil, err
	}

	// 2) Mapear el input a la solicitud atómica
	atomicRequest := familyResolver.mapCreateInputToAtomicRequest(&input)

	// 3) Crear familia de forma atómica (Member + Family + Familiares en una transacción)
	return r.familyService.CreateFamilyAtomic(ctx, atomicRequest)
}

// UpdateFamily is the resolver for the updateFamily field.
func (r *mutationResolver) UpdateFamily(ctx context.Context, input model.UpdateFamilyInput) (*models.Family, error) {
	// Solo ADMIN puede actualizar familias
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// 1) Validación opcional
	familyResolver, ok := r.Family().(*familyResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}

	if err := familyResolver.validateUpdateFamilyInput(&input); err != nil {
		return nil, err
	}

	// 2) Convertir el string "familia_id" en uint (si parseID hace eso)
	id, err := parseID(input.FamiliaID)
	if err != nil {
		return nil, err
	}

	// 3) Buscar la familia existente (usando familyService)
	existing, err := r.familyService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 4) Mapear los campos actualizables al modelo
	updated := familyResolver.mapUpdateInputToFamily(&input, existing)

	// 5) Manejar la mutación / persistir cambios
	return familyResolver.handleFamilyMutation(ctx, updated)
}

// AddFamilyMember is the resolver for the addFamilyMember field.
func (r *mutationResolver) AddFamilyMember(ctx context.Context, familyID string, familiar model.FamiliarInput) (*models.Family, error) {
	// Solo ADMIN puede agregar familiares
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	// 1) parseamos el ID
	id, err := parseID(familyID)
	if err != nil {
		return nil, err
	}

	// 2) obtener la familia
	existing, err := r.familyService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 3) mapear el FamiliarInput a *models.Familiar
	familyResolver, ok := r.Family().(*familyResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	fam := familyResolver.mapFamiliarInputToModel(&familiar)

	// 4) aquí, según tu capa de dominio, podrías:
	//    - Llamar a un método "AddFamilyMember(ctx, existing, fam)"
	//       *O* hacerlo dentro de una nueva función "handleAddFamilyMember"

	// Supongamos que familyService expone "AddFamilyMember"
	err = r.familyService.AddFamiliar(ctx, existing.ID, fam)
	if err != nil {
		return nil, err
	}

	// 5) Retornas la familia ya con el nuevo familiar agregado
	return existing, nil
}

// RemoveFamilyMember is the resolver for the removeFamilyMember field.
func (r *mutationResolver) RemoveFamilyMember(ctx context.Context, familiarID string) (*model.MutationResponse, error) {
	// Solo ADMIN puede remover familiares
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	// 1) parsear ID
	famID, err := parseID(familiarID)
	if err != nil {
		return nil, err
	}

	// 2) llamar a un método en familyService para eliminarlo
	err = r.familyService.RemoveFamiliar(ctx, famID)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, err
	}

	// 3) retornar respuesta de éxito
	msg := "Familiar successfully removed"
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// RegisterPayment is the resolver for the registerPayment field.
func (r *mutationResolver) RegisterPayment(ctx context.Context, input model.PaymentInput) (*models.Payment, error) {
	// Solo ADMIN puede registrar pagos
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	// 1) mapear el input GraphQL al modelo de dominio
	paymentResolver, ok := r.Payment().(*paymentResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	payment := paymentResolver.mapPaymentInputToModel(&input)

	// 2) llamar a la función que valida y persiste
	return paymentResolver.handlePaymentMutation(ctx, payment)
}

// UpdatePayment is the resolver for the updatePayment field.
func (r *mutationResolver) UpdatePayment(ctx context.Context, id string, input model.PaymentInput) (*models.Payment, error) {
	// Solo ADMIN puede actualizar pagos
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	paymentID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 1) obtener el pago actual (opcional, para decidir si está cancelado o no)
	existing, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Payment")
	}

	// 2) mapear input a Payment
	//    (puedes usar mapPaymentInputToModel y luego asignar payment.ID = paymentID)
	paymentResolver, ok := r.Payment().(*paymentResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	updated := paymentResolver.mapPaymentInputToModel(&input)
	updated.ID = paymentID

	// 3) manejar la mutación
	return paymentResolver.handlePaymentMutation(ctx, updated)
}

// CancelPayment is the resolver for the cancelPayment field.
func (r *mutationResolver) CancelPayment(ctx context.Context, id string, reason string) (*model.MutationResponse, error) {
	// Solo ADMIN puede cancelar pagos
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	paymentID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 1) obtener el pago
	existing, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return nil, err // Retornar el error directamente
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Payment") // Retornar error not found
	}

	// 2) si ya está cancelado, devuelves error o idempotencia
	if existing.Status == models.PaymentStatusCancelled {
		return &model.MutationResponse{
			Success: false,
			Error:   stringPtr("Payment is already cancelled"),
		}, nil
	}

	// 3) llamar a un método de tu servicio
	if err := r.paymentService.CancelPayment(ctx, paymentID, reason); err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{Success: false, Error: &errMsg}, err
	}

	// 4) devolver éxito
	msg := "Payment cancelled successfully"
	return &model.MutationResponse{Success: true, Message: &msg}, nil
}

// ConfirmPayment is the resolver for the confirmPayment field.
func (r *mutationResolver) ConfirmPayment(ctx context.Context, id string, paymentMethod string, paymentDate *time.Time, notes *string) (*models.Payment, error) {
	// Solo ADMIN puede confirmar pagos
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Parsear el ID de string a uint
	paymentID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// Llamar al servicio de dominio para confirmar el pago
	payment, err := r.paymentService.ConfirmPayment(ctx, paymentID, paymentMethod, paymentDate, notes)
	if err != nil {
		return nil, err
	}

	return payment, nil
}

// RegisterFee is the resolver for the registerFee field.
func (r *mutationResolver) RegisterFee(ctx context.Context, year int, baseAmount float64) (*model.MutationResponse, error) {
	// Solo ADMIN puede registrar cuotas
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	// Validación básica de los parámetros
	if year < 2000 || year > 2100 {
		return nil, appErrors.NewValidationError(
			"Invalid year",
			map[string]string{"year": "Year must be between 2000 and 2100"},
		)
	}

	if baseAmount <= 0 {
		return nil, appErrors.NewValidationError(
			"Invalid base amount",
			map[string]string{"baseAmount": "Base amount must be greater than zero"},
		)
	}

	// 1) Crear la cuota de membresía anual para ese año en la BD
	err := r.paymentService.GenerateAnnualFee(ctx, year, baseAmount)
	if err != nil {
		return nil, err
	}

	// 2) Devolver un mensaje confirmando la operación
	msg := fmt.Sprintf("Membership fee for year %d has been generated successfully", year)
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// GenerateAnnualFees is the resolver for the generateAnnualFees field.
func (r *mutationResolver) GenerateAnnualFees(ctx context.Context, input model.GenerateAnnualFeesInput) (*model.GenerateAnnualFeesResponse, error) {
	// Solo ADMIN puede generar cuotas anuales
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Convertir input GraphQL a request del servicio
	req := &inputPorts.GenerateAnnualFeesRequest{
		Year:           input.Year,
		BaseFeeAmount:  input.BaseFeeAmount,
		FamilyFeeExtra: input.FamilyFeeExtra,
	}

	// Llamar al servicio
	result, err := r.paymentService.GenerateAnnualFees(ctx, req)
	if err != nil {
		return nil, err
	}

	// Convertir response del servicio a GraphQL
	response := &model.GenerateAnnualFeesResponse{
		Year:                result.Year,
		MembershipFeeID:     fmt.Sprintf("%d", result.MembershipFeeID),
		PaymentsGenerated:   result.PaymentsGenerated,
		PaymentsExisting:    result.PaymentsExisting,
		TotalMembers:        result.TotalMembers,
		TotalExpectedAmount: result.TotalExpectedAmount,
		Details:             make([]*model.PaymentGenerationDetail, len(result.Details)),
	}

	// Convertir detalles
	for i, detail := range result.Details {
		errorMsg := detail.Error
		response.Details[i] = &model.PaymentGenerationDetail{
			MemberID:     fmt.Sprintf("%d", detail.MemberID),
			MemberNumber: detail.MemberNumber,
			MemberName:   detail.MemberName,
			Amount:       detail.Amount,
			WasCreated:   detail.WasCreated,
			Error:        &errorMsg,
		}
	}

	return response, nil
}

// CreateCashFlow is the resolver for the createCashFlow field.
func (r *mutationResolver) CreateCashFlow(ctx context.Context, input model.CreateCashFlowInput) (*models.CashFlow, error) {
	// Solo ADMIN puede crear movimientos de caja manualmente
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Convertir CreateCashFlowInput a TransactionInput (son idénticos)
	transactionInput := model.TransactionInput(input)

	// Usar el mismo flujo que RegisterTransaction
	cashFlowResolver, ok := r.CashFlow().(*cashFlowResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	transaction := cashFlowResolver.mapTransactionInputToModel(&transactionInput)

	// Manejar la lógica de validación y persistencia
	return cashFlowResolver.handleTransactionMutation(ctx, transaction)
}

// UpdateCashFlow is the resolver for the updateCashFlow field.
func (r *mutationResolver) UpdateCashFlow(ctx context.Context, id string, input model.UpdateCashFlowInput) (*models.CashFlow, error) {
	// Solo ADMIN puede actualizar movimientos de caja
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Parsear el ID
	cashFlowID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// Obtener el movimiento existente
	existing, err := r.cashFlowService.GetMovement(ctx, cashFlowID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NotFound("cash flow", nil)
	}

	// Actualizar solo los campos proporcionados
	if input.OperationType != nil {
		existing.OperationType = *input.OperationType
	}
	if input.Amount != nil {
		existing.Amount = *input.Amount
	}
	if input.Date != nil {
		existing.Date = *input.Date
	}
	if input.Detail != nil {
		existing.Detail = *input.Detail
	}

	// Validar y persistir
	cashFlowResolver, ok := r.CashFlow().(*cashFlowResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}

	return cashFlowResolver.handleTransactionMutation(ctx, existing)
}

// DeleteCashFlow is the resolver for the deleteCashFlow field.
func (r *mutationResolver) DeleteCashFlow(ctx context.Context, id string) (*model.MutationResponse, error) {
	// Solo ADMIN puede eliminar movimientos de caja
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Parsear el ID
	cashFlowID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// Verificar que el movimiento existe
	existing, err := r.cashFlowService.GetMovement(ctx, cashFlowID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NotFound("cash flow", nil)
	}

	// Verificar que no esté asociado a un pago
	// Los movimientos generados automáticamente por pagos no deberían eliminarse manualmente
	if existing.PaymentID != nil {
		return &model.MutationResponse{
			Success: false,
			Error:   stringPtr("No se puede eliminar un movimiento de caja generado automáticamente por un pago. Debe cancelar el pago en su lugar."),
		}, nil
	}

	// Eliminar el movimiento
	if err := r.cashFlowService.DeleteMovement(ctx, cashFlowID); err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, err
	}

	msg := "Cash flow movement deleted successfully"
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// AdjustBalance is the resolver for the adjustBalance field.
func (r *mutationResolver) AdjustBalance(ctx context.Context, amount float64, reason string) (*model.MutationResponse, error) {
	// Solo ADMIN puede ajustar balance
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	cashFlowResolver, ok := r.CashFlow().(*cashFlowResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	return cashFlowResolver.handleBalanceAdjustment(ctx, amount, reason)
}

// RegisterTransaction is the resolver for the registerTransaction field.
// schema.resolvers.go
func (r *mutationResolver) RegisterTransaction(ctx context.Context, input model.TransactionInput) (*models.CashFlow, error) {
	// Solo ADMIN puede registrar transacciones
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	// 1) Mapear el input a tu entidad de dominio
	cashFlowResolver, ok := r.CashFlow().(*cashFlowResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	transaction := cashFlowResolver.mapTransactionInputToModel(&input)

	// 2) Manejar la lógica de validación y persistencia
	return cashFlowResolver.handleTransactionMutation(ctx, transaction)
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input model.TransactionInput) (*models.CashFlow, error) {
	// Solo ADMIN puede actualizar transacciones
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	transactionID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// Comprobar si existe
	existing, err := r.cashFlowService.GetMovement(ctx, transactionID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Transaction")
	}

	// mapear input a un *nuevo* CashFlow
	cashFlowResolver, ok := r.CashFlow().(*cashFlowResolver)
	if !ok {
		return nil, appErrors.NewInternalError("invalid resolver type")
	}
	updatedTx := cashFlowResolver.mapTransactionInputToModel(&input)
	// forzar el ID para que la capa de persistencia sepa que es un update
	updatedTx.ID = transactionID

	// persistir
	return cashFlowResolver.handleTransactionMutation(ctx, updatedTx)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	// Llamamos a la función implementada en auth_resolver.go
	return r.Resolver.Login(ctx, input)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.MutationResponse, error) {
	// Llamamos a la función implementada en auth_resolver.go
	return r.Resolver.Logout(ctx)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.TokenResponse, error) {
	// Llamamos a la función implementada en auth_resolver.go
	return r.Resolver.RefreshToken(ctx, input)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*models.User, error) {
	// Solo ADMIN puede crear usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	// Solo ADMIN puede actualizar usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.UpdateUser(ctx, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.MutationResponse, error) {
	// Solo ADMIN puede eliminar usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.DeleteUser(ctx, id)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (*model.MutationResponse, error) {
	return r.Resolver.ChangePassword(ctx, input)
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, userID string, newPassword string) (*model.MutationResponse, error) {
	// Solo ADMIN puede resetear contraseñas de otros usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.ResetUserPassword(ctx, userID, newPassword)
}

// SendVerificationEmail is the resolver for the sendVerificationEmail field.
func (r *mutationResolver) SendVerificationEmail(ctx context.Context) (*model.MutationResponse, error) {
	return r.Resolver.SendVerificationEmail(ctx)
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.MutationResponse, error) {
	return r.Resolver.VerifyEmail(ctx, token)
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context, email string) (*model.MutationResponse, error) {
	return r.Resolver.ResendVerificationEmail(ctx, email)
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (*model.MutationResponse, error) {
	return r.Resolver.RequestPasswordReset(ctx, email)
}

// ResetPasswordWithToken is the resolver for the resetPasswordWithToken field.
func (r *mutationResolver) ResetPasswordWithToken(ctx context.Context, token string, newPassword string) (*model.MutationResponse, error) {
	return r.Resolver.ResetPasswordWithToken(ctx, token, newPassword)
}

// ID is the resolver for the id field.
func (r *paymentResolver) ID(ctx context.Context, obj *models.Payment) (string, error) {
	// Asumiendo que obj.ID es de tipo uint
	return fmt.Sprintf("%d", obj.ID), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "Service is healthy", nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*models.User, error) {
	// Solo ADMIN puede ver detalles de otros usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.GetUser(ctx, id)
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, page *int, pageSize *int) ([]*models.User, error) {
	// Solo ADMIN puede listar usuarios
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}
	return r.Resolver.ListUsers(ctx, page, pageSize)
}

// GetCurrentUser is the resolver for the getCurrentUser field.
func (r *queryResolver) GetCurrentUser(ctx context.Context) (*models.User, error) {
	return r.Resolver.GetCurrentUser(ctx)
}

// GetMember is the resolver for the getMember field.
func (r *queryResolver) GetMember(ctx context.Context, id string) (*models.Member, error) {
	memberID, err := parseID(id) // Convierte el string en uint
	if err != nil {
		return nil, err
	}

	// Verificar permisos de acceso
	if err := middleware.CanAccessMember(ctx, memberID); err != nil {
		return nil, err
	}

	member, err := r.memberService.GetMemberByID(ctx, memberID)
	if err != nil {
		return nil, err
	}
	if member == nil {
		return nil, appErrors.NewNotFoundError("Member")
	}

	return member, nil
}

// ListMembers is the resolver for the listMembers field.
func (r *queryResolver) ListMembers(ctx context.Context, filter *model.MemberFilter) (*model.MemberConnection, error) {
	// Obtener el MemberID del usuario actual
	memberID, err := middleware.GetMemberIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Si memberID es nil, es admin - mostrar todo
	if memberID == nil {
		// Comportamiento para ADMIN: usar métodos helper
		domainFilter := r.mapMemberFilterToDomain(filter)

		// Llamar al servicio
		members, err := r.memberService.ListMembers(ctx, domainFilter)
		if err != nil {
			return nil, err
		}

		// Construir y retornar la respuesta usando el método helper
		return r.buildMemberConnection(members, domainFilter.Page), nil
	}

	// USER: solo puede ver su propio registro
	member, err := r.memberService.GetMemberByID(ctx, *memberID)
	if err != nil {
		return nil, err
	}

	if member == nil {
		return &model.MemberConnection{
			Nodes: []*models.Member{},
			PageInfo: &model.PageInfo{
				TotalCount:      0,
				HasNextPage:     false,
				HasPreviousPage: false,
			},
		}, nil
	}

	return &model.MemberConnection{
		Nodes: []*models.Member{member},
		PageInfo: &model.PageInfo{
			TotalCount:      1,
			HasNextPage:     false,
			HasPreviousPage: false,
		},
	}, nil
}

// SearchMembers is the resolver for the searchMembers field.
func (r *queryResolver) SearchMembers(ctx context.Context, criteria string) ([]*models.Member, error) {
	// Obtener el MemberID del usuario actual
	memberID, err := middleware.GetMemberIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Si memberID es nil, es admin - hacer búsqueda completa
	if memberID == nil {
		// 1) Construir un MemberFilters con pageSize muy grande
		domainFilter := inputPorts.MemberFilters{
			SearchTerm: &criteria,
			Page:       1,
			PageSize:   999999, // suposición: "sin tope"
		}

		// 2) Llamar a r.memberService.ListMembers
		members, err := r.memberService.ListMembers(ctx, domainFilter)
		if err != nil {
			return nil, err
		}

		// 3) Convertir a []*models.Member
		result := make([]*models.Member, len(members))
		for i, m := range members {
			mm := m
			result[i] = mm
		}

		return result, nil
	}

	// USER: solo puede buscar su propio registro
	member, err := r.memberService.GetMemberByID(ctx, *memberID)
	if err != nil {
		return nil, err
	}

	if member == nil {
		return []*models.Member{}, nil
	}

	// Solo devolver el registro si coincide con el criterio de búsqueda
	if containsIgnoreCase(member.Name, criteria) ||
		containsIgnoreCase(member.Surnames, criteria) ||
		containsIgnoreCase(member.MembershipNumber, criteria) {
		return []*models.Member{member}, nil
	}

	return []*models.Member{}, nil
}

// SearchMembersWithoutUser is the resolver for the searchMembersWithoutUser field.
func (r *queryResolver) SearchMembersWithoutUser(ctx context.Context, criteria string) ([]*models.Member, error) {
	// Solo ADMIN puede buscar miembros sin usuario
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Llamar al servicio para buscar miembros sin usuario asociado
	members, err := r.memberService.SearchMembersWithoutUser(ctx, criteria)
	if err != nil {
		return nil, err
	}

	return members, nil
}

// GetFamily is the resolver for the getFamily field.
func (r *queryResolver) GetFamily(ctx context.Context, id string) (*models.Family, error) {
	// 1) parsear el id de string a uint (o lo que tu parseID retorne)
	familyID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 2) llamar a tu servicio de familias
	family, err := r.familyService.GetByID(ctx, familyID)
	if err != nil {
		return nil, err
	}

	// 3) si no existe, retornar un error de "no encontrado"
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// Verificar permisos de acceso
	if err := middleware.CanAccessFamily(ctx, family.MiembroOrigenID); err != nil {
		return nil, err
	}

	// 4) retornar la familia
	return family, nil
}

// GetFamilyByOriginMember is the resolver for the getFamilyByOriginMember field.
func (r *queryResolver) GetFamilyByOriginMember(ctx context.Context, memberID string) (*models.Family, error) {
	// Parse member ID from string to uint
	id, err := parseID(memberID)
	if err != nil {
		return nil, fmt.Errorf("invalid member ID: %w", err)
	}

	// Call family service to get family by origin member ID
	family, err := r.familyService.GetByOriginMemberID(ctx, id)
	if err != nil {
		return nil, err
	}

	// Verify access permissions if family exists
	if family != nil {
		if err := middleware.CanAccessFamily(ctx, family.MiembroOrigenID); err != nil {
			return nil, err
		}
	}

	return family, nil
}

// ListFamilies is the resolver for the listFamilies field.
func (r *queryResolver) ListFamilies(ctx context.Context, filter *model.FamilyFilter) (*model.FamilyConnection, error) {
	// Obtener el MemberID del usuario actual
	memberID, err := middleware.GetMemberIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Si memberID es nil, es admin - mostrar todo
	if memberID == nil {
		// Comportamiento original para ADMIN
		// 1) valores por defecto
		page := 1
		pageSize := 10
		var searchTerm *string
		var orderBy string

		// 2) Extraer fields del filtro
		if filter != nil {
			// paginación
			if filter.Pagination != nil {
				page = filter.Pagination.Page
				pageSize = filter.Pagination.PageSize
			}
			// searchTerm
			if filter.SearchTerm != nil {
				searchTerm = filter.SearchTerm
			}
			// sort (campo + dirección)
			if filter.Sort != nil {
				orderBy = fmt.Sprintf("%s %s", filter.Sort.Field, filter.Sort.Direction)
			}
		}

		// 3) Llamar a tu servicio / repositorio para obtener la lista
		families, totalCount, err := r.familyService.List(ctx, page, pageSize, searchTerm, orderBy)
		if err != nil {
			return nil, err
		}

		// 4) Construir PageInfo
		pageInfo := &model.PageInfo{
			HasNextPage:     (page * pageSize) < totalCount,
			HasPreviousPage: page > 1,
			TotalCount:      totalCount,
		}

		// 5) Retornar la conexión
		return &model.FamilyConnection{
			Nodes:    families, // []*models.Family
			PageInfo: pageInfo,
		}, nil
	}

	// USER: solo puede ver familias donde es el miembro origen
	// Obtener todas las familias y filtrar
	families, _, err := r.familyService.List(ctx, 1, 1000, nil, "")
	if err != nil {
		return nil, err
	}

	// Filtrar solo las familias donde el usuario es miembro origen
	var userFamilies []*models.Family
	for _, family := range families {
		if family.MiembroOrigenID != nil && *family.MiembroOrigenID == *memberID {
			userFamilies = append(userFamilies, family)
		}
	}

	return &model.FamilyConnection{
		Nodes: userFamilies,
		PageInfo: &model.PageInfo{
			TotalCount:      len(userFamilies),
			HasNextPage:     false,
			HasPreviousPage: false,
		},
	}, nil
}

// GetFamilyMembers is the resolver for the getFamilyMembers field.
func (r *queryResolver) GetFamilyMembers(ctx context.Context, familyID string) ([]*models.Familiar, error) {
	// 1) Parsear el ID
	fid, err := parseID(familyID)
	if err != nil {
		return nil, err
	}

	// 2) Verificar que la familia existe (opcional)
	family, err := r.familyService.GetByID(ctx, fid)
	if err != nil {
		return nil, err
	}
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// Verificar permisos de acceso a la familia
	if err := middleware.CanAccessFamily(ctx, family.MiembroOrigenID); err != nil {
		return nil, err
	}

	// 3) Obtener la lista de familiares
	familiares, err := r.familyService.GetFamiliares(ctx, fid)
	if err != nil {
		return nil, err
	}

	// 4) Devolver el slice de familiares
	return familiares, nil
}

// GetPayment is the resolver for the getPayment field.
func (r *queryResolver) GetPayment(ctx context.Context, id string) (*models.Payment, error) {
	// 1) parsear el ID de string a uint (u otro tipo interno)
	paymentID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 2) llamar a tu servicio de pagos para obtener el pago
	payment, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return nil, err
	}

	// 3) si no se encuentra, retornar un error "not found"
	if payment == nil {
		return nil, appErrors.NewNotFoundError("Payment")
	}

	// Verificar permisos de acceso
	if err := middleware.CanAccessPayment(ctx, &payment.MemberID); err != nil {
		return nil, err
	}

	// 4) retornar el payment
	return payment, nil
}

// GetMemberPayments is the resolver for the getMemberPayments field.
func (r *queryResolver) GetMemberPayments(ctx context.Context, memberID string) ([]*models.Payment, error) {
	// 1) parsear el string "memberID" a uint
	mid, err := parseID(memberID)
	if err != nil {
		return nil, err
	}

	// Verificar permisos de acceso al miembro
	if err := middleware.CanAccessMember(ctx, mid); err != nil {
		return nil, err
	}

	// 2) Buscar los pagos del miembro
	payments, err := r.paymentService.GetMemberPayments(ctx, mid)
	if err != nil {
		return nil, err
	}

	// 3) Retornar el slice
	return payments, nil
}

// GetFamilyPayments is the resolver for the getFamilyPayments field.
func (r *queryResolver) GetFamilyPayments(ctx context.Context, familyID string) ([]*models.Payment, error) {
	// 1) parsear la cadena "familyID" a uint
	fid, err := parseID(familyID)
	if err != nil {
		return nil, err
	}

	// 2) (opcional) verificar que la familia exista
	family, err := r.familyService.GetByID(ctx, fid)
	if err != nil {
		return nil, err
	}
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// Verificar permisos de acceso a la familia
	if err := middleware.CanAccessFamily(ctx, family.MiembroOrigenID); err != nil {
		return nil, err
	}

	// 3) buscar los pagos de la familia
	payments, err := r.paymentService.GetFamilyPayments(ctx, fid)
	if err != nil {
		return nil, err
	}

	// 4) retornar el slice
	return payments, nil
}

// GetPaymentStatus is the resolver for the getPaymentStatus field.
func (r *queryResolver) GetPaymentStatus(ctx context.Context, id string) (models.PaymentStatus, error) {
	// 1) parsear el string "id" a uint (u otro tipo interno)
	paymentID, err := parseID(id)
	if err != nil {
		return "", err
	}

	// 2) obtener el pago
	payment, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return "", err
	}
	if payment == nil {
		return "", appErrors.NewNotFoundError("Payment")
	}

	// Verificar permisos de acceso al pago
	if err := middleware.CanAccessPayment(ctx, &payment.MemberID); err != nil {
		return "", err
	}

	// 3) retornar el status (ej. PaymentStatusPaid, PaymentStatusCancelled, etc.)
	return payment.Status, nil
}

// ListPayments is the resolver for the listPayments field.
func (r *queryResolver) ListPayments(ctx context.Context, filter *model.PaymentFilter) (*model.PaymentConnection, error) {
	// Only ADMIN can list all payments
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Map GraphQL filter to domain filter
	filters, err := r.mapPaymentFilterToDomain(filter)
	if err != nil {
		return nil, err
	}

	// Call service
	payments, total, err := r.paymentService.ListPayments(ctx, filters)
	if err != nil {
		return nil, err
	}

	// Calculate pagination info
	totalPages := (total + filters.PageSize - 1) / filters.PageSize
	hasNextPage := filters.Page < totalPages
	hasPreviousPage := filters.Page > 1

	// Build PageInfo
	pageInfo := &model.PageInfo{
		HasNextPage:     hasNextPage,
		HasPreviousPage: hasPreviousPage,
		TotalCount:      total,
	}

	return &model.PaymentConnection{
		Nodes:    payments,
		PageInfo: pageInfo,
	}, nil
}

// GetMembershipFee is the resolver for the getMembershipFee field.
func (r *queryResolver) GetMembershipFee(ctx context.Context, year int) (*models.MembershipFee, error) {
	// Solo ADMIN puede consultar cuotas
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Llamar al servicio de pagos (month = 0, ignorado en cuotas anuales)
	return r.paymentService.GetMembershipFee(ctx, year, 0)
}

// ListMembershipFees is the resolver for the listMembershipFees field.
func (r *queryResolver) ListMembershipFees(ctx context.Context, page *int, pageSize *int) ([]*models.MembershipFee, error) {
	// Solo ADMIN puede listar cuotas
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// TODO: Implementar método FindAll en el repositorio cuando sea necesario
	// Por ahora retornamos un error de operación inválida
	return nil, appErrors.New(appErrors.ErrInvalidOperation, "listMembershipFees no implementado aún")
}

// GetPendingFees is the resolver for the getPendingFees field.
func (r *queryResolver) GetPendingFees(ctx context.Context) ([]*models.MembershipFee, error) {
	// Solo ADMIN puede consultar cuotas pendientes
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// TODO: Implementar método GetAllPendingFees en el servicio
	// Por ahora retornamos un error de operación inválida
	return nil, appErrors.New(appErrors.ErrInvalidOperation, "getPendingFees no implementado aún")
}

// GetCashFlow is the resolver for the getCashFlow field.
func (r *queryResolver) GetCashFlow(ctx context.Context, id string) (*models.CashFlow, error) {
	// Solo ADMIN puede ver transacciones individuales
	// Los usuarios USER no deben acceder a transacciones directamente
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// 1) Parsear el string a uint
	cfID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	// 2) Llamar a tu servicio para obtener la transacción
	cashFlow, err := r.cashFlowService.GetMovement(ctx, cfID)
	if err != nil {
		return nil, err
	}

	// 3) Verificar si no se encontró
	if cashFlow == nil {
		return nil, appErrors.NewNotFoundError("CashFlow")
	}

	// 4) Retornar el objeto CashFlow
	return cashFlow, nil
}

// CashFlowBalance is the resolver for the cashFlowBalance field.
func (r *queryResolver) CashFlowBalance(ctx context.Context) (*model.CashFlowBalance, error) {
	// Verificar autenticación
	if err := middleware.MustBeAuthenticated(ctx); err != nil {
		return nil, err
	}

	// Obtener MemberID del contexto (nil para admin, memberID para user)
	memberID, err := middleware.GetMemberIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Obtener el balance actual
	balanceReport, err := r.cashFlowService.GetCurrentBalance(ctx)
	if err != nil {
		return nil, err
	}

	// Si es un usuario normal (no admin), necesitamos filtrar por su memberID
	// GetCurrentBalance devuelve el balance global, necesitamos obtenerlo específico
	if memberID != nil {
		// TODO: Implementar GetBalanceByMember en el servicio
		// Por ahora, los usuarios normales no deberían ver este query
		return nil, appErrors.NewBusinessError(
			appErrors.ErrForbidden,
			"Los usuarios solo pueden ver sus transacciones, no el balance global",
		)
	}

	// Construir la respuesta para admin
	return &model.CashFlowBalance{
		TotalIncome:    balanceReport.TotalIncome,
		TotalExpenses:  balanceReport.TotalExpenses,
		CurrentBalance: balanceReport.CurrentBalance,
	}, nil
}

// CashFlowStats is the resolver for the cashFlowStats field.
func (r *queryResolver) CashFlowStats(ctx context.Context, startDate time.Time, endDate time.Time) (*model.CashFlowStats, error) {
	panic(fmt.Errorf("not implemented: CashFlowStats - cashFlowStats"))
}

// GetTransactions is the resolver for the getTransactions field.
func (r *queryResolver) GetTransactions(ctx context.Context, filter *model.TransactionFilter) (*model.TransactionConnection, error) {
	// Verificar autenticación
	if err := middleware.MustBeAuthenticated(ctx); err != nil {
		return nil, err
	}

	// Obtener MemberID del contexto (nil para admin, memberID para user)
	memberID, err := middleware.GetMemberIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	page := 1
	pageSize := 10
	var orderBy string
	var startDate, endDate *time.Time
	var operationType *models.OperationType
	var filterMemberID *uint

	if filter != nil {
		if filter.Pagination != nil {
			page = filter.Pagination.Page
			pageSize = filter.Pagination.PageSize
		}
		if filter.Sort != nil {
			orderBy = fmt.Sprintf("%s %s", filter.Sort.Field, filter.Sort.Direction)
		}
		if filter.StartDate != nil {
			startDate = filter.StartDate
		}
		if filter.EndDate != nil {
			endDate = filter.EndDate
		}
		if filter.OperationType != nil {
			op := *filter.OperationType
			operationType = &op
		}
		// Si viene memberID en el filtro (solo admin puede usarlo)
		if filter.MemberID != nil {
			parsedID, err := parseID(*filter.MemberID)
			if err == nil {
				filterMemberID = &parsedID
			}
		}
	}

	// Si el usuario es USER (no admin), forzar el filtro por su memberID
	if memberID != nil {
		filterMemberID = memberID
	}

	cfFilter := inputPorts.CashFlowFilter{
		StartDate:     startDate,
		EndDate:       endDate,
		OperationType: operationType,
		MemberID:      filterMemberID,
		Page:          page,
		PageSize:      pageSize,
		OrderBy:       orderBy,
	}

	// Llamar al servicio
	movements, err := r.cashFlowService.GetMovementsByPeriod(ctx, cfFilter)
	if err != nil {
		return nil, err
	}

	// Construir PageInfo, con paginación "incompleta" (no tenemos total real)
	pageInfo := &model.PageInfo{
		HasNextPage:     false, // sin total real, no sabemos si hay más
		HasPreviousPage: page > 1,
		TotalCount:      len(movements), // no es el total global, solo la página actual
	}

	return &model.TransactionConnection{
		Nodes:    movements,
		PageInfo: pageInfo,
	}, nil
}

// GetBalance is the resolver for the getBalance field.
func (r *queryResolver) GetBalance(ctx context.Context) (float64, error) {
	// Solo ADMIN puede ver el balance general
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return 0, err
	}

	// 1) Llamas a un método de tu servicio (p. ej. "GetCurrentBalance")
	balance, err := r.cashFlowService.GetCurrentBalance(ctx)
	if err != nil {
		return 0, err
	}

	// 2) Retornas el valor numérico
	return balance.CurrentBalance, nil
}

// GetNextMemberNumber is the resolver for the getNextMemberNumber field.
func (r *queryResolver) GetNextMemberNumber(ctx context.Context, isFamily bool) (string, error) {
	// Llamar directamente al servicio de miembros
	return r.memberService.GetNextMemberNumber(ctx, isFamily)
}

// CheckMemberNumberExists is the resolver for the checkMemberNumberExists field.
func (r *queryResolver) CheckMemberNumberExists(ctx context.Context, memberNumber string) (bool, error) {
	// Llamar directamente al servicio de miembros
	return r.memberService.CheckMemberNumberExists(ctx, memberNumber)
}

// CheckDocumentValidity is the resolver for the checkDocumentValidity field.
func (r *queryResolver) CheckDocumentValidity(ctx context.Context, documentNumber string) (*model.DocumentValidationResult, error) {
	// Importar el paquete de validación
	isValid := validation.ValidarNIF(documentNumber)

	result := &model.DocumentValidationResult{
		IsValid: isValid,
	}

	if isValid {
		// Si es válido, devolver el valor normalizado
		normalized := validation.NormalizarNIF(documentNumber)
		result.NormalizedValue = &normalized
	} else {
		// Si no es válido, proporcionar un mensaje de error descriptivo
		var errorMsg string

		// Verificar casos específicos de error
		normalized := validation.NormalizarNIF(documentNumber)
		switch {
		case len(normalized) != 9:
			errorMsg = "El documento debe tener exactamente 9 caracteres (sin espacios ni guiones)"
		case normalized[0] != 'X' && normalized[0] != 'Y' && normalized[0] != 'Z' && (normalized[0] < '0' || normalized[0] > '9'):
			errorMsg = "El documento debe empezar con un número (DNI) o con X, Y o Z (NIE)"
		default:
			errorMsg = "La letra de control no es correcta"
		}

		result.ErrorMessage = &errorMsg
	}

	return result, nil
}

// GetDashboardStats is the resolver for the getDashboardStats field.
func (r *queryResolver) GetDashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	// Solo ADMIN puede ver las estadísticas del dashboard
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Delegar al dashboard resolver
	dashboardResolver := &dashboardResolver{r.Resolver}
	return dashboardResolver.GetDashboardStats(ctx)
}

// GetRecentActivity is the resolver for the getRecentActivity field.
func (r *queryResolver) GetRecentActivity(ctx context.Context, limit *int) ([]*model.RecentActivity, error) {
	// Solo ADMIN puede ver la actividad reciente
	if err := middleware.MustBeAdmin(ctx); err != nil {
		return nil, err
	}

	// Delegar al dashboard resolver
	dashboardResolver := &dashboardResolver{r.Resolver}
	return dashboardResolver.GetRecentActivity(ctx, limit)
}

// GetDelinquentReport is the resolver for the getDelinquentReport field.
func (r *queryResolver) GetDelinquentReport(ctx context.Context, input *model.DelinquentReportInput) (*model.DelinquentReportResponse, error) {
	return r.Resolver.GetDelinquentReport(ctx, input)
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *models.User) (model.UserRole, error) {
	// Convertir el role del modelo a UserRole
	switch obj.Role {
	case models.RoleAdmin:
		return model.UserRoleAdmin, nil
	case models.RoleUser:
		return model.UserRoleUser, nil
	default:
		// Este caso no debería ocurrir si los datos están bien validados
		return model.UserRoleUser, nil
	}
}

// CashFlow returns generated.CashFlowResolver implementation.
func (r *Resolver) CashFlow() generated.CashFlowResolver { return &cashFlowResolver{r} }

// Familiar returns generated.FamiliarResolver implementation.
func (r *Resolver) Familiar() generated.FamiliarResolver { return &familiarResolver{r} }

// Family returns generated.FamilyResolver implementation.
func (r *Resolver) Family() generated.FamilyResolver { return &familyResolver{r} }

// Member returns generated.MemberResolver implementation.
func (r *Resolver) Member() generated.MemberResolver { return &memberResolver{r} }

// MembershipFee returns generated.MembershipFeeResolver implementation.
func (r *Resolver) MembershipFee() generated.MembershipFeeResolver { return &membershipFeeResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type cashFlowResolver struct{ *Resolver }
type familiarResolver struct{ *Resolver }
type familyResolver struct{ *Resolver }
type memberResolver struct{ *Resolver }
type membershipFeeResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type paymentResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
