package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"fmt"

	"github.com/javicabdev/asam-backend/internal/adapters/gql/generated"
	"github.com/javicabdev/asam-backend/internal/adapters/gql/model"
	"github.com/javicabdev/asam-backend/internal/domain/models"
)

// MiembroID is the resolver for the miembro_id field.
func (r *memberResolver) MiembroID(ctx context.Context, obj *models.Member) (string, error) {
	panic(fmt.Errorf("not implemented: MiembroID - miembro_id"))
}

// TipoMembresia is the resolver for the tipo_membresia field.
func (r *memberResolver) TipoMembresia(ctx context.Context, obj *models.Member) (model.MembershipType, error) {
	panic(fmt.Errorf("not implemented: TipoMembresia - tipo_membresia"))
}

// Estado is the resolver for the estado field.
func (r *memberResolver) Estado(ctx context.Context, obj *models.Member) (model.MemberStatus, error) {
	panic(fmt.Errorf("not implemented: Estado - estado"))
}

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "¡Bienvenido a la API de ASAM!", nil
}

// Member returns generated.MemberResolver implementation.
func (r *Resolver) Member() generated.MemberResolver { return &memberResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type memberResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
