package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"fmt"
	"time"

	"github.com/javicabdev/asam-backend/internal/adapters/gql/generated"
	"github.com/javicabdev/asam-backend/internal/adapters/gql/model"
	"github.com/javicabdev/asam-backend/internal/domain/models"
	"github.com/javicabdev/asam-backend/internal/ports/input"
	appErrors "github.com/javicabdev/asam-backend/pkg/errors"
)

// ID is the resolver for the id field.
func (r *cashFlowResolver) ID(ctx context.Context, obj *models.CashFlow) (string, error) {
	// Asumiendo que obj.ID es de tipo uint o uint64
	return fmt.Sprintf("%d", obj.ID), nil
}

// ID is the resolver for the id field.
func (r *familiarResolver) ID(ctx context.Context, obj *models.Familiar) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// ID is the resolver for the id field.
func (r *familyResolver) ID(ctx context.Context, obj *models.Family) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// MiembroID is the resolver for the miembro_id field.
func (r *memberResolver) MiembroID(ctx context.Context, obj *models.Member) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// TipoMembresia is the resolver for the tipo_membresia field.
func (r *memberResolver) TipoMembresia(ctx context.Context, obj *models.Member) (model.MembershipType, error) {
	switch obj.TipoMembresia {
	case models.TipoMembresiaPIndividual: // "individual"
		return model.MembershipTypeIndividual, nil
	case models.TipoMembresiaPFamiliar: // "familiar"
		return model.MembershipTypeFamily, nil
	default:
		return "",
			appErrors.NewValidationError(
				fmt.Sprintf("tipo_membresia desconocido: %s", obj.TipoMembresia),
				map[string]string{"tipo_membresia": "desconocido"},
			)
	}
}

// Estado is the resolver for the estado field.
func (r *memberResolver) Estado(ctx context.Context, obj *models.Member) (model.MemberStatus, error) {
	switch obj.Estado {
	case models.EstadoActivo: // "activo"
		return model.MemberStatusActive, nil
	case models.EstadoInactivo: // "inactivo"
		return model.MemberStatusInactive, nil
	default:
		return "",
			appErrors.NewValidationError(
				fmt.Sprintf("estado desconocido: %s", obj.TipoMembresia),
				map[string]string{"estado": "desconocido"},
			)
	}
}

// CreateMember is the resolver for the createMember field.
func (r *mutationResolver) CreateMember(ctx context.Context, input model.CreateMemberInput) (*models.Member, error) {
	// 1) Invocar alguna validación (si la tienes en member_resolver.go):
	if err := r.Member().(*memberResolver).validateCreateInput(&input); err != nil {
		return nil, err
	}

	// 2) Mapear el input al dominio
	member, err := r.Member().(*memberResolver).mapCreateInputToMember(&input)
	if err != nil {
		return nil, err
	}

	// 3) Manejar la mutación en la capa de servicio
	return r.Member().(*memberResolver).handleMemberMutation(ctx, member)
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, input model.UpdateMemberInput) (*models.Member, error) {
	// 1) Validar input si corresponde
	if err := r.Member().(*memberResolver).validateUpdateInput(&input); err != nil {
		return nil, err
	}

	// 2) Convertir el string MiembroID a uint (si parseID hace eso)
	id := parseID(input.MiembroID)

	// 3) Buscar el member existente (si procede)
	existing, err := r.memberService.GetMemberByID(ctx, id)
	if err != nil {
		return nil, err
	}
	// Opcionalmente, manejar el caso de "no encontrado"
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Member")
	}

	// 4) Mapear los campos de UpdateMemberInput a la entidad
	member := r.Member().(*memberResolver).mapUpdateInputToMember(id, &input, existing)

	// 5) Manejar la mutación / guardar cambios
	return r.Member().(*memberResolver).handleMemberMutation(ctx, member)
}

// DeleteMember is the resolver for the deleteMember field.
func (r *mutationResolver) DeleteMember(ctx context.Context, id string) (*model.MutationResponse, error) {
	err := r.memberService.DeactivateMember(ctx, parseID(id), nil)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, nil
	}
	msg := "Member successfully deleted"
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// ChangeMemberStatus is the resolver for the changeMemberStatus field.
func (r *mutationResolver) ChangeMemberStatus(ctx context.Context, id string, status model.MemberStatus) (*models.Member, error) {
	// 1) Parsear el ID a uint (o el tipo que uses internamente)
	memberID := parseID(id)

	// 2) Llamar al método handleMemberStatus del sub-resolver (member_resolver.go)
	return r.Member().(*memberResolver).handleMemberStatus(ctx, memberID, status)
}

// CreateFamily is the resolver for the createFamily field.
func (r *mutationResolver) CreateFamily(ctx context.Context, input model.CreateFamilyInput) (*models.Family, error) {
	// 1) Validar input (opcional, si tienes validateCreateFamilyInput)
	if err := r.Family().(*familyResolver).validateCreateFamilyInput(&input); err != nil {
		return nil, err
	}

	// 2) Mapear el input a la entidad del dominio
	family := r.Family().(*familyResolver).mapCreateInputToFamily(&input)

	// 3) Manejar la mutación / guardar en BD
	return r.Family().(*familyResolver).handleFamilyMutation(ctx, family)
}

// UpdateFamily is the resolver for the updateFamily field.
func (r *mutationResolver) UpdateFamily(ctx context.Context, input model.UpdateFamilyInput) (*models.Family, error) {
	// 1) Validación opcional
	if err := r.Family().(*familyResolver).validateUpdateFamilyInput(&input); err != nil {
		return nil, err
	}

	// 2) Convertir el string "familia_id" en uint (si parseID hace eso)
	id := parseID(input.FamiliaID)

	// 3) Buscar la familia existente (usando familyService)
	existing, err := r.familyService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 4) Mapear los campos actualizables al modelo
	updated := r.Family().(*familyResolver).mapUpdateInputToFamily(&input, existing)

	// 5) Manejar la mutación / persistir cambios
	return r.Family().(*familyResolver).handleFamilyMutation(ctx, updated)
}

// AddFamilyMember is the resolver for the addFamilyMember field.
func (r *mutationResolver) AddFamilyMember(ctx context.Context, familyID string, familiar model.FamiliarInput) (*models.Family, error) {
	// 1) parseamos el ID
	id := parseID(familyID)

	// 2) obtener la familia
	existing, err := r.familyService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 3) mapear el FamiliarInput a *models.Familiar
	fam := r.Family().(*familyResolver).mapFamiliarInputToModel(&familiar)

	// 4) aquí, según tu capa de dominio, podrías:
	//    - Llamar a un método "AddFamilyMember(ctx, existing, fam)"
	//       *O* hacerlo dentro de una nueva función "handleAddFamilyMember"

	// Supongamos que familyService expone "AddFamilyMember"
	err = r.familyService.AddFamiliar(ctx, existing.ID, fam)
	if err != nil {
		return nil, err
	}

	// 5) Retornas la familia ya con el nuevo familiar agregado
	return existing, nil
}

// RemoveFamilyMember is the resolver for the removeFamilyMember field.
func (r *mutationResolver) RemoveFamilyMember(ctx context.Context, familiarID string) (*model.MutationResponse, error) {
	// 1) parsear ID
	famID := parseID(familiarID)

	// 2) llamar a un método en familyService para eliminarlo
	err := r.familyService.RemoveFamiliar(ctx, famID)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	// 3) retornar respuesta de éxito
	msg := "Familiar successfully removed"
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// RegisterPayment is the resolver for the registerPayment field.
func (r *mutationResolver) RegisterPayment(ctx context.Context, input model.PaymentInput) (*models.Payment, error) {
	// 1) mapear el input GraphQL al modelo de dominio
	payment := r.Payment().(*paymentResolver).mapPaymentInputToModel(&input)

	// 2) llamar a la función que valida y persiste
	return r.Payment().(*paymentResolver).handlePaymentMutation(ctx, payment)
}

// UpdatePayment is the resolver for the updatePayment field.
func (r *mutationResolver) UpdatePayment(ctx context.Context, id string, input model.PaymentInput) (*models.Payment, error) {
	paymentID := parseID(id)

	// 1) obtener el pago actual (opcional, para decidir si está cancelado o no)
	existing, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Payment")
	}

	// 2) mapear input a Payment
	//    (puedes usar mapPaymentInputToModel y luego asignar payment.ID = paymentID)
	updated := r.Payment().(*paymentResolver).mapPaymentInputToModel(&input)
	updated.ID = paymentID

	// 3) manejar la mutación
	return r.Payment().(*paymentResolver).handlePaymentMutation(ctx, updated)
}

// CancelPayment is the resolver for the cancelPayment field.
func (r *mutationResolver) CancelPayment(ctx context.Context, id string, reason string) (*model.MutationResponse, error) {
	paymentID := parseID(id)

	// 1) obtener el pago
	existing, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{Success: false, Error: &errMsg}, nil
	}
	if existing == nil {
		return &model.MutationResponse{Success: false, Error: stringPtr("Payment")}, nil
	}

	// 2) si ya está cancelado, devuelves error o idempotencia
	if existing.Status == models.PaymentStatusCancelled {
		return &model.MutationResponse{
			Success: false,
			Error:   stringPtr("Payment is already cancelled"),
		}, nil
	}

	// 3) llamar a un método de tu servicio
	if err := r.paymentService.CancelPayment(ctx, paymentID, reason); err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{Success: false, Error: &errMsg}, nil
	}

	// 4) devolver éxito
	msg := "Payment cancelled successfully"
	return &model.MutationResponse{Success: true, Message: &msg}, nil
}

// RegisterFee is the resolver for the registerFee field.
func (r *mutationResolver) RegisterFee(ctx context.Context, year int, month int, baseAmount float64) (*model.MutationResponse, error) {
	// 1) Crear la cuota de membresía para ese mes/año en la BD
	err := r.paymentService.GenerateMonthlyFees(ctx, year, month, baseAmount)
	if err != nil {
		errMsg := err.Error()
		return &model.MutationResponse{
			Success: false,
			Error:   &errMsg,
		}, nil
	}

	// 2) Devolver un mensaje confirmando la operación
	msg := fmt.Sprintf("Membership fee for %d-%02d has been generated successfully", year, month)
	return &model.MutationResponse{
		Success: true,
		Message: &msg,
	}, nil
}

// RegisterTransaction is the resolver for the registerTransaction field.
// schema.resolvers.go
func (r *mutationResolver) RegisterTransaction(ctx context.Context, input model.TransactionInput) (*models.CashFlow, error) {
	// 1) Mapear el input a tu entidad de dominio
	transaction := r.CashFlow().(*cashFlowResolver).mapTransactionInputToModel(&input)

	// 2) Manejar la lógica de validación y persistencia
	return r.CashFlow().(*cashFlowResolver).handleTransactionMutation(ctx, transaction)
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input model.TransactionInput) (*models.CashFlow, error) {
	transactionID := parseID(id)

	// Comprobar si existe
	existing, err := r.cashFlowService.GetMovement(ctx, transactionID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, appErrors.NewNotFoundError("Transaction")
	}

	// mapear input a un *nuevo* CashFlow
	updatedTx := r.CashFlow().(*cashFlowResolver).mapTransactionInputToModel(&input)
	// forzar el ID para que la capa de persistencia sepa que es un update
	updatedTx.ID = transactionID

	// persistir
	return r.CashFlow().(*cashFlowResolver).handleTransactionMutation(ctx, updatedTx)
}

// AdjustBalance is the resolver for the adjustBalance field.
func (r *mutationResolver) AdjustBalance(ctx context.Context, amount float64, reason string) (*model.MutationResponse, error) {
	return r.CashFlow().(*cashFlowResolver).handleBalanceAdjustment(ctx, amount, reason)
}

// ID is the resolver for the id field.
func (r *paymentResolver) ID(ctx context.Context, obj *models.Payment) (string, error) {
	// Asumiendo que obj.ID es de tipo uint
	return fmt.Sprintf("%d", obj.ID), nil
}

// GetMember is the resolver for the getMember field.
func (r *queryResolver) GetMember(ctx context.Context, id string) (*models.Member, error) {
	memberID := parseID(id) // Convierte el string en uint
	member, err := r.memberService.GetMemberByID(ctx, memberID)
	if err != nil {
		return nil, err
	}
	if member == nil {
		return nil, appErrors.NewNotFoundError("Member")
	}

	return member, nil
}

// ListMembers is the resolver for the listMembers field.
func (r *queryResolver) ListMembers(ctx context.Context, filter *model.MemberFilter) (*model.MemberConnection, error) {
	// 1) Definir valores por defecto
	page := 1
	pageSize := 10
	var estado *string
	var tipoMembresia *string
	var searchTerm *string
	var orderBy string

	// 2) Extraer paginación si `filter` no es nil
	if filter != nil {
		if filter.Pagination != nil {
			page = filter.Pagination.Page
			pageSize = filter.Pagination.PageSize
		}
		// 3) Estado (ACTIVE / INACTIVE) → (activo / inactivo)
		if filter.Estado != nil {
			tmp := ""
			switch *filter.Estado {
			case model.MemberStatusActive:
				tmp = models.EstadoActivo // "activo"
			case model.MemberStatusInactive:
				tmp = models.EstadoInactivo // "inactivo"
			}
			estado = &tmp
		}
		// 4) Tipo de membresía (INDIVIDUAL / FAMILY) → (individual / familiar)
		if filter.TipoMembresia != nil {
			tmp := ""
			switch *filter.TipoMembresia {
			case model.MembershipTypeIndividual:
				tmp = models.TipoMembresiaPIndividual // "individual"
			case model.MembershipTypeFamily:
				tmp = models.TipoMembresiaPFamiliar // "familiar"
			}
			tipoMembresia = &tmp
		}
		// 5) searchTerm
		if filter.SearchTerm != nil {
			searchTerm = filter.SearchTerm
		}
		// 6) Sort (ejemplo: "NOMBRE ASC")
		if filter.Sort != nil {
			orderBy = fmt.Sprintf("%s %s", filter.Sort.Field, filter.Sort.Direction)
		}
	}

	// 7) Crear el struct domain.MemberFilters
	domainFilter := input.MemberFilters{
		Estado:        estado,
		TipoMembresia: tipoMembresia,
		SearchTerm:    searchTerm,
		Page:          page,
		PageSize:      pageSize,
		OrderBy:       orderBy,
	}

	// 8) Llamar al servicio
	members, err := r.memberService.ListMembers(ctx, domainFilter)
	if err != nil {
		return nil, err
	}

	// 9) Tu servicio, por ahora, retorna ([]models.Member, error).
	//    No veo un 'totalCount' en la firma, así que no sabremos cuántas hay en total.
	//    Si lo necesitas, deberías cambiar tu servicio para que devuelva también un total (p.ej. (members []models.Member, total int, err error)).

	// 10) Convertir []models.Member a []*models.Member
	memberPtrs := make([]*models.Member, len(members))
	for i, m := range members {
		// crear un puntero a la variable local (cuidado con &m en range)
		mm := m
		memberPtrs[i] = mm
	}

	// 11) Construir el PageInfo (sin total real, sólo un placeholder)
	pageInfo := &model.PageInfo{
		HasNextPage:     false, // sin totalCount, no podemos saberlo
		HasPreviousPage: page > 1,
		TotalCount:      len(members), // o 0, si no es representativo
	}

	// 12) Retornar MemberConnection
	return &model.MemberConnection{
		Nodes:    memberPtrs,
		PageInfo: pageInfo,
	}, nil
}

// SearchMembers is the resolver for the searchMembers field.
func (r *queryResolver) SearchMembers(ctx context.Context, criteria string) ([]*models.Member, error) {
	// 1) Construir un MemberFilters con pageSize muy grande
	domainFilter := input.MemberFilters{
		SearchTerm: &criteria,
		Page:       1,
		PageSize:   999999, // suposición: "sin tope"
	}

	// 2) Llamar a r.memberService.ListMembers
	members, err := r.memberService.ListMembers(ctx, domainFilter)
	if err != nil {
		return nil, err
	}

	// 3) Convertir a []*models.Member
	result := make([]*models.Member, len(members))
	for i, m := range members {
		mm := m
		result[i] = mm
	}

	return result, nil
}

// GetFamily is the resolver for the getFamily field.
func (r *queryResolver) GetFamily(ctx context.Context, id string) (*models.Family, error) {
	// 1) parsear el id de string a uint (o lo que tu parseID retorne)
	familyID := parseID(id)

	// 2) llamar a tu servicio de familias
	family, err := r.familyService.GetByID(ctx, familyID)
	if err != nil {
		return nil, err
	}

	// 3) si no existe, retornar un error de "no encontrado"
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 4) retornar la familia
	return family, nil
}

// ListFamilies is the resolver for the listFamilies field.
func (r *queryResolver) ListFamilies(ctx context.Context, filter *model.FamilyFilter) (*model.FamilyConnection, error) {
	// 1) valores por defecto
	page := 1
	pageSize := 10
	var searchTerm *string
	var orderBy string

	// 2) Extraer fields del filtro
	if filter != nil {
		// paginación
		if filter.Pagination != nil {
			page = filter.Pagination.Page
			pageSize = filter.Pagination.PageSize
		}
		// searchTerm
		if filter.SearchTerm != nil {
			searchTerm = filter.SearchTerm
		}
		// sort (campo + dirección)
		if filter.Sort != nil {
			orderBy = fmt.Sprintf("%s %s", filter.Sort.Field, filter.Sort.Direction)
		}
	}

	// 3) Llamar a tu servicio / repositorio para obtener la lista
	families, totalCount, err := r.familyService.List(ctx, page, pageSize, searchTerm, orderBy)
	if err != nil {
		return nil, err
	}

	// 4) Construir PageInfo
	pageInfo := &model.PageInfo{
		HasNextPage:     (page * pageSize) < totalCount,
		HasPreviousPage: page > 1,
		TotalCount:      totalCount,
	}

	// 5) Retornar la conexión
	return &model.FamilyConnection{
		Nodes:    families, // []*models.Family
		PageInfo: pageInfo,
	}, nil
}

// GetFamilyMembers is the resolver for the getFamilyMembers field.
func (r *queryResolver) GetFamilyMembers(ctx context.Context, familyID string) ([]*models.Familiar, error) {
	// 1) Parsear el ID
	fid := parseID(familyID)

	// 2) Verificar que la familia existe (opcional)
	family, err := r.familyService.GetByID(ctx, fid)
	if err != nil {
		return nil, err
	}
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 3) Obtener la lista de familiares
	familiares, err := r.familyService.GetFamiliares(ctx, fid)
	if err != nil {
		return nil, err
	}

	// 4) Devolver el slice de familiares
	return familiares, nil
}

// GetPayment is the resolver for the getPayment field.
func (r *queryResolver) GetPayment(ctx context.Context, id string) (*models.Payment, error) {
	// 1) parsear el ID de string a uint (u otro tipo interno)
	paymentID := parseID(id)

	// 2) llamar a tu servicio de pagos para obtener el pago
	payment, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return nil, err
	}

	// 3) si no se encuentra, retornar un error "not found"
	if payment == nil {
		return nil, appErrors.NewNotFoundError("Payment")
	}

	// 4) retornar el payment
	return payment, nil
}

// GetMemberPayments is the resolver for the getMemberPayments field.
func (r *queryResolver) GetMemberPayments(ctx context.Context, memberID string) ([]*models.Payment, error) {
	// 1) parsear el string "memberID" a uint
	mid := parseID(memberID)

	// 2) Buscar los pagos del miembro
	payments, err := r.paymentService.GetMemberPayments(ctx, mid)
	if err != nil {
		return nil, err
	}

	// 3) Retornar el slice
	return payments, nil
}

// GetFamilyPayments is the resolver for the getFamilyPayments field.
func (r *queryResolver) GetFamilyPayments(ctx context.Context, familyID string) ([]*models.Payment, error) {
	// 1) parsear la cadena "familyID" a uint
	fid := parseID(familyID)

	// 2) (opcional) verificar que la familia exista
	family, err := r.familyService.GetByID(ctx, fid)
	if err != nil {
		return nil, err
	}
	if family == nil {
		return nil, appErrors.NewNotFoundError("Family")
	}

	// 3) buscar los pagos de la familia
	payments, err := r.paymentService.GetFamilyPayments(ctx, fid)
	if err != nil {
		return nil, err
	}

	// 4) retornar el slice
	return payments, nil
}

// GetPaymentStatus is the resolver for the getPaymentStatus field.
func (r *queryResolver) GetPaymentStatus(ctx context.Context, id string) (models.PaymentStatus, error) {
	// 1) parsear el string "id" a uint (u otro tipo interno)
	paymentID := parseID(id)

	// 2) obtener el pago
	payment, err := r.paymentService.GetPayment(ctx, paymentID)
	if err != nil {
		return "", err
	}
	if payment == nil {
		return "", appErrors.NewNotFoundError("Payment")
	}

	// 3) retornar el status (ej. PaymentStatusPaid, PaymentStatusCancelled, etc.)
	return payment.Status, nil
}

// GetCashFlow is the resolver for the getCashFlow field.
func (r *queryResolver) GetCashFlow(ctx context.Context, id string) (*models.CashFlow, error) {
	// 1) Parsear el string a uint
	cfID := parseID(id)

	// 2) Llamar a tu servicio para obtener la transacción
	cashFlow, err := r.cashFlowService.GetMovement(ctx, cfID)
	if err != nil {
		return nil, err
	}

	// 3) Verificar si no se encontró
	if cashFlow == nil {
		return nil, appErrors.NewNotFoundError("CashFlo")
	}

	// 4) Retornar el objeto CashFlow
	return cashFlow, nil
}

// GetBalance is the resolver for the getBalance field.
func (r *queryResolver) GetBalance(ctx context.Context) (float64, error) {
	// 1) Llamas a un método de tu servicio (p. ej. "GetCurrentBalance")
	balance, err := r.cashFlowService.GetCurrentBalance(ctx)
	if err != nil {
		return 0, err
	}

	// 2) Retornas el valor numérico
	return balance.CurrentBalance, nil
}

// GetTransactions is the resolver for the getTransactions field.
func (r *queryResolver) GetTransactions(ctx context.Context, filter *model.TransactionFilter) (*model.TransactionConnection, error) {
	page := 1
	pageSize := 10
	var orderBy string
	var startDate, endDate *time.Time
	var operationType *models.OperationType

	if filter != nil {
		if filter.Pagination != nil {
			page = filter.Pagination.Page
			pageSize = filter.Pagination.PageSize
		}
		if filter.Sort != nil {
			orderBy = fmt.Sprintf("%s %s", filter.Sort.Field, filter.Sort.Direction)
		}
		if filter.StartDate != nil {
			startDate = filter.StartDate
		}
		if filter.EndDate != nil {
			endDate = filter.EndDate
		}
		if filter.OperationType != nil {
			op := *filter.OperationType
			operationType = &op
		}
	}

	cfFilter := input.CashFlowFilter{
		StartDate:     startDate,
		EndDate:       endDate,
		OperationType: operationType,
		Page:          page,
		PageSize:      pageSize,
		OrderBy:       orderBy,
	}

	// Llamar al servicio
	movements, err := r.cashFlowService.GetMovementsByPeriod(ctx, cfFilter)
	if err != nil {
		return nil, err
	}

	// Construir PageInfo, con paginación "incompleta" (no tenemos total real)
	pageInfo := &model.PageInfo{
		HasNextPage:     false, // sin total real, no sabemos si hay más
		HasPreviousPage: page > 1,
		TotalCount:      len(movements), // no es el total global, solo la página actual
	}

	return &model.TransactionConnection{
		Nodes:    movements,
		PageInfo: pageInfo,
	}, nil
}

// CashFlow returns generated.CashFlowResolver implementation.
func (r *Resolver) CashFlow() generated.CashFlowResolver { return &cashFlowResolver{r} }

// Familiar returns generated.FamiliarResolver implementation.
func (r *Resolver) Familiar() generated.FamiliarResolver { return &familiarResolver{r} }

// Family returns generated.FamilyResolver implementation.
func (r *Resolver) Family() generated.FamilyResolver { return &familyResolver{r} }

// Member returns generated.MemberResolver implementation.
func (r *Resolver) Member() generated.MemberResolver { return &memberResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type cashFlowResolver struct{ *Resolver }
type familiarResolver struct{ *Resolver }
type familyResolver struct{ *Resolver }
type memberResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type paymentResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
