version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "javicabdev"
    assignees:
      - "javicabdev"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-patches:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    reviewers:
      - "javicabdev"
    assignees:
      - "javicabdev"
    commit-message:
      prefix: "ci"
      include: "scope"
