#!/bin/bash
# Fix invalid SARIF format generated by gosec
# This script removes fixes entries that have null artifactChanges

set -e

SARIF_FILE="${1:-gosec-results.sarif}"

if [ ! -f "$SARIF_FILE" ]; then
    echo "Error: SARIF file not found: $SARIF_FILE"
    exit 1
fi

echo "Fixing SARIF format in $SARIF_FILE..."

# Use jq to remove fixes arrays that contain entries with null artifactChanges
# SARIF spec requires artifactChanges to have at least 1 element if present
jq '
  .runs[].results[] |= (
    if .fixes then
      . + {fixes: [.fixes[] | select(.artifactChanges != null)]} |
      if .fixes | length == 0 then
        del(.fixes)
      else
        .
      end
    else
      .
    end
  )
' "$SARIF_FILE" > "${SARIF_FILE}.tmp"

# Replace the original file
mv "${SARIF_FILE}.tmp" "$SARIF_FILE"

echo "SARIF file fixed successfully!"
