hábla#!/bin/bash
# Fix invalid SARIF format generated by gosec
# This script fixes the artifactChanges field in fixes arrays to be an empty array instead of null

set -e

SARIF_FILE="${1:-gosec-results.sarif}"

if [ ! -f "$SARIF_FILE" ]; then
    echo "Error: SARIF file not found: $SARIF_FILE"
    exit 1
fi

echo "Fixing SARIF format in $SARIF_FILE..."

# Use jq to fix null artifactChanges to empty arrays
# Walk through all results, and for each fix, if artifactChanges is null, set it to []
jq '
  .runs[].results[] |= (
    if .fixes then
      .fixes |= map(
        if .artifactChanges == null then
          .artifactChanges = []
        else
          .
        end
      )
    else
      .
    end
  )
' "$SARIF_FILE" > "${SARIF_FILE}.tmp"

# Replace the original file
mv "${SARIF_FILE}.tmp" "$SARIF_FILE"

echo "SARIF file fixed successfully!"
