# Archivo de configuración para golangci-lint v2.1.6
version: "2"

run:
  go: '1.24'
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
    - revive
    - unconvert
    - gocyclo


issues:
  max-same-issues: 300
