services:
  api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: asam-backend-api-test
    environment:
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=asam_test_db
      - DB_SSL_MODE=disable
      - JWT_ACCESS_SECRET=test_secret
      - JWT_REFRESH_SECRET=test_refresh_secret
    volumes:
      - .:/go/src/github.com/javicabdev/asam-backend
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - asam-test-network

  postgres-test:
    image: postgres:14-alpine
    container_name: asam-postgres-test
    environment:
      - CGO_ENABLED=1
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=asam_test_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - asam-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asam_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  asam-test-network:
    driver: bridge