services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: asam-backend-api
    ports:
      - "${PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - asam-network
    volumes:
      - .:/app # Montar el código fuente para desarrollo
      - /app/tmp # Montar el directorio binario
      - /go/pkg/mod # Montar el cache de módulos de Go
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: asam-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - asam-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  asam-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
