package generators

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/jmoiron/sqlx"
)

// MemberIDInfo holds only the ID of a member.
type MemberIDInfo struct {
	MiembroID int `db:"miembro_id"`
}

// FamilyIDInfo holds only the ID of a family.
type FamilyIDInfo struct {
	FamiliaID int `db:"familia_id"`
}

// CashflowGenerator generates test cash movements (caja)
type CashflowGenerator struct {
	db   *sqlx.DB
	rand *rand.Rand
	// Pre-defined operation types and details for efficiency
	operationTypes   []string
	operationDetails map[string][]string
}

// Cashflow represents a caja record for generation
type Cashflow struct {
	CajaID        int       `db:"caja_id"` // Auto-generated by DB
	MiembroID     *int      `db:"miembro_id"`
	FamiliaID     *int      `db:"familia_id"`
	TipoOperacion string    `db:"tipo_operacion"`
	Monto         float64   `db:"monto"`
	Fecha         time.Time `db:"fecha"`
	Detalle       string    `db:"detalle"`
}

// NewCashflowGenerator creates a new cashflow generator
func NewCashflowGenerator(db *sqlx.DB, seed int64) *CashflowGenerator {
	return &CashflowGenerator{
		db:   db,
		rand: rand.New(rand.NewSource(seed)),
		operationTypes: []string{
			"ingreso_cuota",
			"gasto_corriente",
			"entrega_fondo",
			"otros_ingresos",
		},
		operationDetails: map[string][]string{
			"ingreso_cuota": {
				"Cuota de membresía anual", "Cuota extraordinaria para evento",
				"Pago atrasado de cuota", "Adelanto de cuota",
			},
			"gasto_corriente": {
				"Material de oficina", "Alquiler del local", "Suministros",
				"Transporte", "Gastos evento comunitario", "Mantenimiento equipos",
				"Pago servicios internet", "Imprenta",
			},
			"entrega_fondo": {
				"Ayuda emergencia familiar", "Fondo para repatriación",
				"Ayuda a familia afectada", "Préstamo personal", "Asistencia médica",
			},
			"otros_ingresos": {
				"Donación particular", "Subvención ayuntamiento", "Ingreso por evento",
				"Venta de comida comunitaria", "Aportación extraordinaria", "Devolución préstamo",
			},
		},
	}
}

// GenerateRandomAmount generates a random float64 amount within a given range.
// This function was also present in payment_generator.go.
// func GenerateRandomAmount(r *rand.Rand, min, max float64) float64 {
// 	if min >= max {
// 		return min
// 	}
// 	return min + r.Float64()*(max-min)
// }

// Generate creates n random cash movements, inserting them in batches.
func (g *CashflowGenerator) Generate(ctx context.Context, n int) error {
	if n <= 0 {
		return nil // Nothing to generate
	}

	var members []MemberIDInfo
	err := g.db.SelectContext(ctx, &members, "SELECT miembro_id FROM miembros WHERE estado = 'activo'")
	if err != nil {
		return fmt.Errorf("failed to get active members: %w", err)
	}
	// It's okay if len(members) is 0, some operations don't require members.

	var families []FamilyIDInfo
	err = g.db.SelectContext(ctx, &families, "SELECT familia_id FROM familias")
	if err != nil {
		return fmt.Errorf("failed to get families: %w", err)
	}
	// It's okay if len(families) is 0.

	tx, err := g.db.BeginTxx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer func(tx *sqlx.Tx) {
		err := tx.Rollback()
		if err != nil {

		}
	}(tx) // nolint:errcheck // Rollback errors are usually secondary to the main error

	batchSize := 100 // Optimal batch size can vary
	for i := 0; i < n; i += batchSize {
		itemsInThisBatch := batchSize
		if i+batchSize > n {
			itemsInThisBatch = n - i
		}

		if err := g.generateAndInsertBatch(ctx, tx, members, families, itemsInThisBatch); err != nil {
			// Rollback is handled by defer, just return the error
			return fmt.Errorf("failed to generate or insert cashflow batch: %w", err)
		}
	}

	return tx.Commit()
}

// determineCashflowAssociation decides if a cashflow is linked to a member or family.
func (g *CashflowGenerator) determineCashflowAssociation(
	operationType string,
	members []MemberIDInfo,
	families []FamilyIDInfo,
) (*int, *int) {
	var miembroID, familiaID *int

	// Helper to get a random member ID if members exist
	getRandomMemberID := func() *int {
		if len(members) > 0 {
			id := members[g.rand.Intn(len(members))].MiembroID
			return &id
		}
		return nil
	}

	// Helper to get a random family ID if families exist
	getRandomFamilyID := func() *int {
		if len(families) > 0 {
			id := families[g.rand.Intn(len(families))].FamiliaID
			return &id
		}
		return nil
	}

	switch operationType {
	case "ingreso_cuota":
		// Associate with a member 80% of the time, otherwise with a family (if available)
		if g.rand.Float64() < 0.80 {
			miembroID = getRandomMemberID()
		} else {
			familiaID = getRandomFamilyID()
		}
		// If the primary choice was unavailable and the other is, try the other.
		if miembroID == nil && familiaID == nil {
			if len(members) > 0 {
				miembroID = getRandomMemberID()
			} else if len(families) > 0 {
				familiaID = getRandomFamilyID()
			}
		}

	case "entrega_fondo":
		// Always try to associate with a member or family
		if g.rand.Float64() < 0.50 {
			miembroID = getRandomMemberID()
			if miembroID == nil { // If no member, try family
				familiaID = getRandomFamilyID()
			}
		} else {
			familiaID = getRandomFamilyID()
			if familiaID == nil { // If no family, try member
				miembroID = getRandomMemberID()
			}
		}
	case "gasto_corriente", "otros_ingresos":
		// Usually not associated, but 20% chance to associate
		if g.rand.Float64() < 0.20 {
			if g.rand.Float64() < 0.50 {
				miembroID = getRandomMemberID()
			} else {
				familiaID = getRandomFamilyID()
			}
		}
	}
	return miembroID, familiaID
}

// determineCashflowAmount generates the monetary amount for the cashflow.
func (g *CashflowGenerator) determineCashflowAmount(operationType string) float64 {
	var amount float64
	switch operationType {
	case "ingreso_cuota":
		amount = GenerateRandomAmount(g.rand, 20, 60)
	case "gasto_corriente":
		amount = -GenerateRandomAmount(g.rand, 30, 500) // Negative for expenses
	case "entrega_fondo":
		amount = -GenerateRandomAmount(g.rand, 100, 1000) // Negative for funds given
	case "otros_ingresos":
		amount = GenerateRandomAmount(g.rand, 50, 2000)
	default:
		amount = 0 // Should not happen if operationType is from predefined list
	}
	return amount
}

// generateSingleCashflowData creates one Cashflow data struct.
func (g *CashflowGenerator) generateSingleCashflowData(
	members []MemberIDInfo,
	families []FamilyIDInfo,
) Cashflow {
	operationType := g.operationTypes[g.rand.Intn(len(g.operationTypes))]
	miembroID, familiaID := g.determineCashflowAssociation(operationType, members, families)
	amount := g.determineCashflowAmount(operationType)

	// Generate date within the last 3 years
	now := time.Now()
	startDate := now.AddDate(-3, 0, 0)
	date := GenerateRandomDate(g.rand, startDate, now)

	// Select a random detail for this operation type
	detailsList := g.operationDetails[operationType]
	detail := ""
	if len(detailsList) > 0 {
		detail = detailsList[g.rand.Intn(len(detailsList))]
	}

	return Cashflow{
		MiembroID:     miembroID,
		FamiliaID:     familiaID,
		TipoOperacion: operationType,
		Monto:         amount,
		Fecha:         date,
		Detalle:       detail,
	}
}

// generateAndInsertBatch generates a batch of cash movements and inserts them.
func (g *CashflowGenerator) generateAndInsertBatch(
	ctx context.Context,
	tx *sqlx.Tx,
	members []MemberIDInfo,
	families []FamilyIDInfo,
	numToGenerateInBatch int,
) error {
	if numToGenerateInBatch <= 0 {
		return nil
	}

	cashflows := make([]Cashflow, 0, numToGenerateInBatch)
	for i := 0; i < numToGenerateInBatch; i++ {
		cashflowEntry := g.generateSingleCashflowData(members, families)
		cashflows = append(cashflows, cashflowEntry)
	}

	if len(cashflows) == 0 {
		// Should only happen if numToGenerateInBatch was 0.
		return nil
	}

	query := `
		INSERT INTO caja (miembro_id, familia_id, tipo_operacion, monto, fecha, detalle)
		VALUES (:miembro_id, :familia_id, :tipo_operacion, :monto, :fecha, :detalle)`

	_, err := tx.NamedExecContext(ctx, query, cashflows)
	if err != nil {
		return fmt.Errorf("failed to insert cashflow batch: %w", err)
	}
	return nil
}

// GetCashflowsByPeriod retrieves cash movements for a given period
func (g *CashflowGenerator) GetCashflowsByPeriod(ctx context.Context, startDate, endDate time.Time) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT caja_id, miembro_id, familia_id, tipo_operacion, monto, fecha, detalle
		FROM caja
		WHERE fecha BETWEEN $1 AND $2
		ORDER BY fecha, caja_id` // Added caja_id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, startDate, endDate)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements for period: %w", err)
	}
	return cashflows, nil
}

// GetCashflowsByType retrieves cash movements for a given operation type
func (g *CashflowGenerator) GetCashflowsByType(ctx context.Context, operationType string) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT caja_id, miembro_id, familia_id, tipo_operacion, monto, fecha, detalle
		FROM caja
		WHERE tipo_operacion = $1
		ORDER BY fecha, caja_id` // Added caja_id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, operationType)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements by type '%s': %w", operationType, err)
	}
	return cashflows, nil
}

// GetCashflowsByMember retrieves cash movements for a given member
func (g *CashflowGenerator) GetCashflowsByMember(ctx context.Context, miembroID int) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT caja_id, miembro_id, familia_id, tipo_operacion, monto, fecha, detalle
		FROM caja
		WHERE miembro_id = $1
		ORDER BY fecha, caja_id` // Added caja_id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, miembroID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements for member %d: %w", miembroID, err)
	}
	return cashflows, nil
}
