// Package generators contiene generadores para poblar la base de datos con datos de prueba
// que se utilizan en entornos de desarrollo y pruebas automatizadas. Estos generadores
// crean datos ficticios pero realistas para simular el comportamiento del sistema.
package generators

import (
	"context"
	"database/sql" // Added for sql.ErrNoRows
	"errors"       // Added for errors.Is (used in Get methods)
	"fmt"
	"log" // Added for logging rollback errors
	"math/rand"
	"time"

	"github.com/jmoiron/sqlx"
)

// MemberIDInfo holds only the ID of a member.
type MemberIDInfo struct {
	MemberID int `db:"id"`
}

// FamilyIDInfo holds only the ID of a family.
type FamilyIDInfo struct {
	FamilyID int `db:"id"`
}

// CashflowGenerator generates test cash movements (caja)
type CashflowGenerator struct {
	db   *sqlx.DB
	rand *rand.Rand
	// Pre-defined operation types and details for efficiency
	operationTypes   []string
	operationDetails map[string][]string
}

// Cashflow represents a cash_flows record for generation
type Cashflow struct {
	ID            int       `db:"id"` // Auto-generated by DB
	MemberID      *int      `db:"member_id"`
	FamilyID      *int      `db:"family_id"`
	OperationType string    `db:"operation_type"`
	Amount        float64   `db:"amount"`
	Date          time.Time `db:"date"`
	Detail        string    `db:"detail"`
}

// NewCashflowGenerator creates a new cashflow generator
func NewCashflowGenerator(db *sqlx.DB, seed int64) *CashflowGenerator {
	return &CashflowGenerator{
		db:   db,
		rand: rand.New(rand.NewSource(seed)),
		operationTypes: []string{
			"ingreso_cuota",
			"gasto_corriente",
			"entrega_fondo",
			"otros_ingresos",
		},
		operationDetails: map[string][]string{
			"ingreso_cuota": {
				"Cuota de membresía anual", "Cuota extraordinaria para evento",
				"Pago atrasado de cuota", "Adelanto de cuota",
			},
			"gasto_corriente": {
				"Material de oficina", "Alquiler del local", "Suministros",
				"Transporte", "Gastos evento comunitario", "Mantenimiento equipos",
				"Pago servicios internet", "Imprenta",
			},
			"entrega_fondo": {
				"Ayuda emergencia familiar", "Fondo para repatriación",
				"Ayuda a familia afectada", "Préstamo personal", "Asistencia médica",
			},
			"otros_ingresos": {
				"Donación particular", "Subvención ayuntamiento", "Ingreso por evento",
				"Venta de comida comunitaria", "Aportación extraordinaria", "Devolución préstamo",
			},
		},
	}
}

// Generate creates n random cash movements, inserting them in batches.
func (g *CashflowGenerator) Generate(ctx context.Context, n int) error {
	if n <= 0 {
		return nil // Nothing to generate
	}

	var members []MemberIDInfo
	err := g.db.SelectContext(ctx, &members, "SELECT id FROM members WHERE state = 'activo'")
	if err != nil {
		return fmt.Errorf("failed to get active members: %w", err)
	}
	// It's okay if len(members) is 0, some operations don't require members.

	var families []FamilyIDInfo
	err = g.db.SelectContext(ctx, &families, "SELECT id FROM families")
	if err != nil {
		return fmt.Errorf("failed to get families: %w", err)
	}
	// It's okay if len(families) is 0.

	tx, err := g.db.BeginTxx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	// Defer rollback. It will be executed if an error occurs or if Commit is not called.
	defer func(txToRollback *sqlx.Tx) {
		// Attempt to rollback. This is a cleanup action.
		// The primary error (if any) from the main function body is more important.
		if rollbackErr := txToRollback.Rollback(); rollbackErr != nil && !errors.Is(rollbackErr, sql.ErrTxDone) {
			// Log the rollback error if it's not sql.ErrTxDone (which means Commit or another Rollback already happened)
			log.Printf("Error during deferred transaction rollback: %v", rollbackErr)
		}
	}(tx)

	batchSize := 100 // Optimal batch size can vary
	for i := 0; i < n; i += batchSize {
		itemsInThisBatch := batchSize
		if i+batchSize > n {
			itemsInThisBatch = n - i
		}

		if err := g.generateAndInsertBatch(ctx, tx, members, families, itemsInThisBatch); err != nil {
			// No need to explicitly call Rollback here, the defer will handle it.
			return fmt.Errorf("failed to generate or insert cashflow batch: %w", err)
		}
	}

	// If all batches succeeded, commit the transaction.
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit transaction: %w", err)
	}
	return nil
}

// attemptSetAssociation tries to associate with a member or family based on probability.
// It prioritizes the choice with higher probability and falls back if the primary choice is unavailable.
func (g *CashflowGenerator) attemptSetAssociation(
	memberProb float64,
	members []MemberIDInfo,
	families []FamilyIDInfo,
) (memberID *int, familyID *int) {
	// Helper to get a random member ID if members exist
	getRandomMemberID := func() *int {
		if len(members) > 0 {
			id := members[g.rand.Intn(len(members))].MemberID
			return &id
		}
		return nil
	}

	// Helper to get a random family ID if families exist
	getRandomFamilyID := func() *int {
		if len(families) > 0 {
			id := families[g.rand.Intn(len(families))].FamilyID
			return &id
		}
		return nil
	}

	if g.rand.Float64() < memberProb { // Prioritize member
		memberID = getRandomMemberID()
		if memberID == nil { // If member assignment failed (e.g., no members)
			familyID = getRandomFamilyID() // Try to assign family as fallback
		}
	} else { // Prioritize family
		familyID = getRandomFamilyID()
		if familyID == nil { // If family assignment failed (e.g., no families)
			memberID = getRandomMemberID() // Try to assign member as fallback
		}
	}
	return memberID, familyID
}

// determineCashflowAssociation decides if a cashflow is linked to a member or family.
func (g *CashflowGenerator) determineCashflowAssociation(
	operationType string,
	members []MemberIDInfo,
	families []FamilyIDInfo,
) (memberID *int, familyID *int) {
	switch operationType {
	case "ingreso_cuota":
		// 80% member, 20% family, with fallback
		return g.attemptSetAssociation(0.80, members, families)
	case "entrega_fondo":
		// 50% member, 50% family, with fallback
		return g.attemptSetAssociation(0.50, members, families)
	case "gasto_corriente", "otros_ingresos":
		// Usually not associated, but 20% chance to associate
		if g.rand.Float64() < 0.20 {
			// If associating, 50/50 chance for member or family
			return g.attemptSetAssociation(0.50, members, families)
		}
		return nil, nil // No association for the 80% case
	}
	// Should ideally not be reached if operationType is always one of the known types.
	// Consider logging a warning or returning an error if operationType is unexpected.
	return nil, nil
}

// determineCashflowAmount generates the monetary amount for the cashflow.
func (g *CashflowGenerator) determineCashflowAmount(operationType string) float64 {
	var amount float64
	switch operationType {
	case "ingreso_cuota":
		amount = GenerateRandomAmount(g.rand, 20, 60)
	case "gasto_corriente":
		amount = -GenerateRandomAmount(g.rand, 30, 500) // Negative for expenses
	case "entrega_fondo":
		amount = -GenerateRandomAmount(g.rand, 100, 1000) // Negative for funds given
	case "otros_ingresos":
		amount = GenerateRandomAmount(g.rand, 50, 2000)
	default:
		amount = 0 // Should not happen if operationType is from predefined list
		log.Printf("Warning: unknown operation type '%s' in determineCashflowAmount, setting amount to 0", operationType)
	}
	return amount
}

// generateSingleCashflowData creates one Cashflow data struct.
func (g *CashflowGenerator) generateSingleCashflowData(
	members []MemberIDInfo,
	families []FamilyIDInfo,
) Cashflow {
	operationType := g.operationTypes[g.rand.Intn(len(g.operationTypes))]
	memberID, familyID := g.determineCashflowAssociation(operationType, members, families)
	amount := g.determineCashflowAmount(operationType)

	// Generate date within the last 3 years
	now := time.Now()
	startDate := now.AddDate(-3, 0, 0)
	date := GenerateRandomDate(g.rand, startDate, now)

	// Select a random detail for this operation type
	detailsList := g.operationDetails[operationType]
	detail := ""
	if len(detailsList) > 0 {
		detail = detailsList[g.rand.Intn(len(detailsList))]
	} else {
		log.Printf("Warning: no details found for operation type '%s'", operationType)
	}

	return Cashflow{
		MemberID:      memberID,
		FamilyID:      familyID,
		OperationType: operationType,
		Amount:        amount,
		Date:          date,
		Detail:        detail,
	}
}

// generateAndInsertBatch generates a batch of cash movements and inserts them.
func (g *CashflowGenerator) generateAndInsertBatch(
	ctx context.Context,
	tx *sqlx.Tx,
	members []MemberIDInfo,
	families []FamilyIDInfo,
	numToGenerateInBatch int,
) error {
	if numToGenerateInBatch <= 0 {
		return nil
	}

	cashflows := make([]Cashflow, 0, numToGenerateInBatch)
	for i := 0; i < numToGenerateInBatch; i++ {
		cashflowEntry := g.generateSingleCashflowData(members, families)
		cashflows = append(cashflows, cashflowEntry)
	}

	if len(cashflows) == 0 {
		// This case should ideally not be hit if numToGenerateInBatch > 0.
		// If it is, it means generateSingleCashflowData is consistently failing to produce data,
		// which might indicate a deeper issue or edge case in data generation logic.
		log.Println("Warning: generateAndInsertBatch produced an empty cashflows slice despite numToGenerateInBatch > 0.")
		return nil
	}

	query := `
		INSERT INTO cash_flows (member_id, family_id, operation_type, amount, date, detail)
		VALUES (:member_id, :family_id, :operation_type, :amount, :date, :detail)`

	_, err := tx.NamedExecContext(ctx, query, cashflows)
	if err != nil {
		return fmt.Errorf("failed to insert cashflow batch: %w", err)
	}
	return nil
}

// GetCashflowsByPeriod retrieves cash movements for a given period
func (g *CashflowGenerator) GetCashflowsByPeriod(ctx context.Context, startDate, endDate time.Time) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT id, member_id, family_id, operation_type, amount, date, detail
		FROM cash_flows
		WHERE date BETWEEN $1 AND $2
		ORDER BY date, id` // Added id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, startDate, endDate)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) { // Use errors.Is for checking specific errors
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements for period: %w", err)
	}
	return cashflows, nil
}

// GetCashflowsByType retrieves cash movements for a given operation type
func (g *CashflowGenerator) GetCashflowsByType(ctx context.Context, operationType string) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT id, member_id, family_id, operation_type, amount, date, detail
		FROM cash_flows
		WHERE operation_type = $1
		ORDER BY date, id` // Added id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, operationType)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements by type '%s': %w", operationType, err)
	}
	return cashflows, nil
}

// GetCashflowsByMember retrieves cash movements for a given member
func (g *CashflowGenerator) GetCashflowsByMember(ctx context.Context, memberID int) ([]Cashflow, error) {
	var cashflows []Cashflow
	query := `
		SELECT id, member_id, family_id, operation_type, amount, date, detail
		FROM cash_flows
		WHERE member_id = $1
		ORDER BY date, id` // Added id for stable sort

	err := g.db.SelectContext(ctx, &cashflows, query, memberID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Cashflow{}, nil
		}
		return nil, fmt.Errorf("failed to get cash movements for member %d: %w", memberID, err)
	}
	return cashflows, nil
}
