package generators

import (
	"context"
	"database/sql" // Used for sql.ErrNoRows, though not directly in this refactor, good practice if Select might return it.
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/jmoiron/sqlx"
)

// MemberInfo holds essential information about a member for payment generation.
type MemberInfo struct {
	MiembroID     int       `db:"miembro_id"`
	FechaAlta     time.Time `db:"fecha_alta"`
	TipoMembresia string    `db:"tipo_membresia"`
}

// PaymentGenerator generates test payments (cuotas_membresia)
type PaymentGenerator struct {
	db   *sqlx.DB
	rand *rand.Rand
}

// Payment represents a cuota_membresia record for generation
type Payment struct {
	CuotaID        int       `db:"cuota_id"` // Typically auto-generated by DB, not set by generator
	MiembroID      int       `db:"miembro_id"`
	Ano            int       `db:"ano"`
	CantidadPagada float64   `db:"cantidad_pagada"`
	FechaPago      time.Time `db:"fecha_pago"`
}

// NewPaymentGenerator creates a new payment generator
func NewPaymentGenerator(db *sqlx.DB, seed int64) *PaymentGenerator {
	return &PaymentGenerator{
		db:   db,
		rand: rand.New(rand.NewSource(seed)),
	}
}

// Generate creates n random payments, inserting them in batches.
func (g *PaymentGenerator) Generate(ctx context.Context, n int) error {
	if n <= 0 {
		return nil // Nothing to generate
	}

	var members []MemberInfo
	// Select active members to associate payments with
	err := g.db.SelectContext(ctx, &members,
		"SELECT miembro_id, fecha_alta, tipo_membresia FROM miembros WHERE estado = 'activo'")
	if err != nil {
		return fmt.Errorf("failed to get active members: %w", err)
	}

	if len(members) == 0 {
		return fmt.Errorf("no active members found to associate payments with. Seed members first")
	}

	tx, err := g.db.BeginTxx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	// Defer rollback, commit will override if successful
	defer func(tx *sqlx.Tx) {
		_ = tx.Rollback()
	}(tx) // nolint:errcheck // Rollback errors are usually secondary

	batchSize := 100 // Optimal batch size can depend on DB and network
	for i := 0; i < n; i += batchSize {
		currentBatchTargetSize := batchSize
		if i+batchSize > n {
			currentBatchTargetSize = n - i
		}

		// The generateBatch function now expects the target number of payments for THIS batch.
		if err := g.generateAndInsertBatch(ctx, tx, members, currentBatchTargetSize); err != nil {
			// Rollback is handled by defer, just return the error
			return fmt.Errorf("failed to generate or insert batch starting at offset %d: %w", i, err)
		}
	}

	return tx.Commit()
}

// generateAndInsertBatch is responsible for generating a single batch of payments up to batchTargetSize
// and inserting them into the database via the provided transaction.
func (g *PaymentGenerator) generateAndInsertBatch(
	ctx context.Context,
	tx *sqlx.Tx,
	members []MemberInfo,
	batchTargetSize int,
) error {
	if batchTargetSize == 0 {
		return nil
	}

	payments := make([]Payment, 0, batchTargetSize)

	// Phase 1: Attempt to generate historical payments for members
	payments = g.populateHistoricalPayments(members, batchTargetSize, payments)

	// Phase 2: If not enough payments, fill with more random ones
	if len(payments) < batchTargetSize {
		payments = g.populateRandomFillPayments(members, batchTargetSize, payments)
	}

	// Ensure the batch is not larger than requested (should be handled by sub-functions, but as a safeguard)
	if len(payments) > batchTargetSize {
		payments = payments[:batchTargetSize]
	}

	if len(payments) == 0 {
		// This might happen if batchTargetSize is small and no valid payments could be generated.
		// Or if members/years don't allow for payment generation.
		// Depending on requirements, this could be an error or just a log.
		// For now, we assume it's okay to have an empty batch if no payments could be made.
		return nil
	}

	// Prepare query for batch insert
	query := `
		INSERT INTO cuotas_membresia (miembro_id, ano, cantidad_pagada, fecha_pago)
		VALUES (:miembro_id, :ano, :cantidad_pagada, :fecha_pago)
		ON CONFLICT (miembro_id, ano) DO NOTHING` // Prevents duplicates at DB level

	_, err := tx.NamedExecContext(ctx, query, payments)
	if err != nil {
		return fmt.Errorf("failed to insert payment batch: %w", err)
	}
	return nil
}

// tryMakePaymentData attempts to generate valid payment data for a given member and year.
// It incorporates the 85% chance, date validation, and amount calculation.
func (g *PaymentGenerator) tryMakePaymentData(member MemberInfo, year int) (Payment, bool) {
	// 85% chance of payment for each year
	if g.rand.Float64() >= 0.85 {
		return Payment{}, false
	}

	// Payment date - sometime during the year
	// Ensure day is valid for the month (e.g. up to 28 for simplicity here)
	paymentMonth := time.Month(g.rand.Intn(12) + 1)
	paymentDay := g.rand.Intn(28) + 1 // Simplification: max 28 days
	paymentDate := time.Date(year, paymentMonth, paymentDay,
		g.rand.Intn(24), g.rand.Intn(60), g.rand.Intn(60), 0, time.UTC)

	// Skip if payment date is in the future (relative to now)
	if paymentDate.After(time.Now()) {
		return Payment{}, false
	}

	// Skip if payment date is before member's join date
	if paymentDate.Before(member.FechaAlta) {
		return Payment{}, false
	}

	// Determine payment amount based on membership type
	var amount float64
	if member.TipoMembresia == "individual" {
		amount = GenerateRandomAmount(g.rand, 20, 40) // Individual membership: 20-40€
	} else {
		amount = GenerateRandomAmount(g.rand, 30, 60) // Family membership: 30-60€
	}

	return Payment{
		MiembroID:      member.MiembroID,
		Ano:            year,
		CantidadPagada: amount,
		FechaPago:      paymentDate,
	}, true
}

// populateHistoricalPayments tries to generate payments based on member history.
// It appends to `currentPayments` until `maxPaymentsInBatch` is reached.
func (g *PaymentGenerator) populateHistoricalPayments(
	members []MemberInfo,
	maxPaymentsInBatch int,
	currentPayments []Payment,
) []Payment {
	currentYear := time.Now().Year()
	// Keep track of (memberID, year) combinations already added in this batch to avoid duplicates from this phase
	addedInThisBatch := make(map[string]struct{})
	for _, p := range currentPayments { // Pre-populate with existing if any (though usually starts empty)
		key := fmt.Sprintf("%d-%d", p.MiembroID, p.Ano)
		addedInThisBatch[key] = struct{}{}
	}

	for _, member := range members {
		if len(currentPayments) >= maxPaymentsInBatch {
			break // Batch is full
		}

		joinYear := member.FechaAlta.Year()
		for year := joinYear; year <= currentYear; year++ {
			if len(currentPayments) >= maxPaymentsInBatch {
				break // Batch is full
			}

			key := fmt.Sprintf("%d-%d", member.MiembroID, year)
			if _, exists := addedInThisBatch[key]; exists {
				continue // Already added or attempted for this member/year in this batch run
			}

			payment, ok := g.tryMakePaymentData(member, year)
			if ok {
				currentPayments = append(currentPayments, payment)
				addedInThisBatch[key] = struct{}{}
			}
		}
	}
	return currentPayments
}

// populateRandomFillPayments tries to generate more payments randomly if the batch isn't full.
// It appends to `currentPayments` until `maxPaymentsInBatch` is reached.
func (g *PaymentGenerator) populateRandomFillPayments(
	members []MemberInfo,
	maxPaymentsInBatch int,
	currentPayments []Payment,
) []Payment {
	currentYear := time.Now().Year()
	// Keep track of (memberID, year) combinations already present in currentPayments
	// to avoid adding true duplicates to the batch.
	existingPaymentKeys := make(map[string]struct{})
	for _, p := range currentPayments {
		key := fmt.Sprintf("%d-%d", p.MiembroID, p.Ano)
		existingPaymentKeys[key] = struct{}{}
	}

	maxAttempts := maxPaymentsInBatch * 5 // Safety break to avoid infinite loops
	attempts := 0

	for len(currentPayments) < maxPaymentsInBatch && attempts < maxAttempts {
		attempts++
		if len(members) == 0 {
			break
		} // Should not happen if initial check passed

		member := members[g.rand.Intn(len(members))]
		joinYear := member.FechaAlta.Year()

		if currentYear < joinYear { // Should not happen if member.FechaAlta is sane
			continue
		}

		// Ensure year range is valid
		yearRange := currentYear - joinYear + 1
		if yearRange <= 0 {
			continue // Cannot pick a year if joinYear > currentYear or joinYear == currentYear and already processed
		}
		year := joinYear + g.rand.Intn(yearRange)

		key := fmt.Sprintf("%d-%d", member.MiembroID, year)
		if _, exists := existingPaymentKeys[key]; exists {
			continue // This (member, year) combo is already in the batch
		}

		payment, ok := g.tryMakePaymentData(member, year)
		if ok {
			currentPayments = append(currentPayments, payment)
			existingPaymentKeys[key] = struct{}{} // Mark as added to this batch
		}
	}
	return currentPayments
}

// GetPaymentsByMember retrieves all payments for a given member
func (g *PaymentGenerator) GetPaymentsByMember(ctx context.Context, miembroID int) ([]Payment, error) {
	var payments []Payment
	query := `
		SELECT cuota_id, miembro_id, ano, cantidad_pagada, fecha_pago
		FROM cuotas_membresia
		WHERE miembro_id = $1
		ORDER BY ano, fecha_pago` // Added fecha_pago to order

	err := g.db.SelectContext(ctx, &payments, query, miembroID)
	if err != nil {
		// It's good practice to check for sql.ErrNoRows if you want to treat "not found" differently from other errors.
		if errors.Is(err, sql.ErrNoRows) {
			return []Payment{}, nil // Return empty slice if no payments found
		}
		return nil, fmt.Errorf("failed to get payments for member %d: %w", miembroID, err)
	}
	return payments, nil
}

// GetPaymentsByYear retrieves all payments for a given year
func (g *PaymentGenerator) GetPaymentsByYear(ctx context.Context, year int) ([]Payment, error) {
	var payments []Payment
	query := `
		SELECT cuota_id, miembro_id, ano, cantidad_pagada, fecha_pago
		FROM cuotas_membresia
		WHERE ano = $1
		ORDER BY miembro_id, fecha_pago` // Added fecha_pago to order

	err := g.db.SelectContext(ctx, &payments, query, year)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Payment{}, nil // Return empty slice if no payments found
		}
		return nil, fmt.Errorf("failed to get payments for year %d: %w", year, err)
	}
	return payments, nil
}
