package generators

import (
	"context"
	"database/sql" // Used for sql.ErrNoRows, though not directly in this refactor, good practice if Select might return it.
	"errors"
	"fmt"
	"math/rand"
	"time"

	"github.com/jmoiron/sqlx"
)

// MemberInfo holds essential information about a member for payment generation.
type MemberInfo struct {
	ID               uint      `db:"id"`
	RegistrationDate time.Time `db:"registration_date"`
	MembershipType   string    `db:"membership_type"`
}

// PaymentGenerator generates test payments
type PaymentGenerator struct {
	db   *sqlx.DB
	rand *rand.Rand
}

// Payment represents a payment record for generation
type Payment struct {
	ID            uint      `db:"id"` // Typically auto-generated by DB, not set by generator
	MemberID      uint      `db:"member_id"`
	Amount        float64   `db:"amount"`
	PaymentDate   time.Time `db:"payment_date"`
	Status        string    `db:"status"`
	PaymentMethod string    `db:"payment_method"`
}

// NewPaymentGenerator creates a new payment generator
func NewPaymentGenerator(db *sqlx.DB, seed int64) *PaymentGenerator {
	// If seed is 0, generate a cryptographically secure seed
	if seed == 0 {
		seed = GenerateSecureSeed()
	}
	return &PaymentGenerator{
		db:   db,
		rand: rand.New(rand.NewSource(seed)), //nolint:gosec // Deterministic random for test data generation
	}
}

// Generate creates n random payments, inserting them in batches.
func (g *PaymentGenerator) Generate(ctx context.Context, n int) error {
	if n <= 0 {
		return nil // Nothing to generate
	}

	var members []MemberInfo
	// Select active members to associate payments with
	err := g.db.SelectContext(ctx, &members,
		"SELECT id, registration_date, membership_type FROM members WHERE state = 'active'")
	if err != nil {
		return fmt.Errorf("failed to get active members: %w", err)
	}

	if len(members) == 0 {
		return fmt.Errorf("no active members found to associate payments with. Seed members first")
	}

	tx, err := g.db.BeginTxx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	// Defer rollback, commit will override if successful
	defer func(tx *sqlx.Tx) {
		_ = tx.Rollback()
	}(tx)

	batchSize := 100 // Optimal batch size can depend on DB and network
	for i := 0; i < n; i += batchSize {
		currentBatchTargetSize := batchSize
		if i+batchSize > n {
			currentBatchTargetSize = n - i
		}

		// The generateBatch function now expects the target number of payments for THIS batch.
		if err := g.generateAndInsertBatch(ctx, tx, members, currentBatchTargetSize); err != nil {
			// Rollback is handled by defer, just return the error
			return fmt.Errorf("failed to generate or insert batch starting at offset %d: %w", i, err)
		}
	}

	return tx.Commit()
}

// generateAndInsertBatch is responsible for generating a single batch of payments up to batchTargetSize
// and inserting them into the database via the provided transaction.
func (g *PaymentGenerator) generateAndInsertBatch(
	ctx context.Context,
	tx *sqlx.Tx,
	members []MemberInfo,
	batchTargetSize int,
) error {
	if batchTargetSize == 0 {
		return nil
	}

	payments := make([]Payment, 0, batchTargetSize)

	// Phase 1: Attempt to generate historical payments for members
	payments = g.populateHistoricalPayments(members, batchTargetSize, payments)

	// Phase 2: If not enough payments, fill with more random ones
	if len(payments) < batchTargetSize {
		payments = g.populateRandomFillPayments(members, batchTargetSize, payments)
	}

	// Ensure the batch is not larger than requested (should be handled by sub-functions, but as a safeguard)
	if len(payments) > batchTargetSize {
		payments = payments[:batchTargetSize]
	}

	if len(payments) == 0 {
		// This might happen if batchTargetSize is small and no valid payments could be generated.
		// Or if members/years don't allow for payment generation.
		// Depending on requirements, this could be an error or just a log.
		// For now, we assume it's okay to have an empty batch if no payments could be made.
		return nil
	}

	// Prepare query for batch insert
	query := `
		INSERT INTO payments (member_id, amount, payment_date, status, payment_method, created_at, updated_at)
		VALUES (:member_id, :amount, :payment_date, :status, :payment_method, NOW(), NOW())
		ON CONFLICT DO NOTHING` // Prevents duplicates at DB level

	_, err := tx.NamedExecContext(ctx, query, payments)
	if err != nil {
		return fmt.Errorf("failed to insert payment batch: %w", err)
	}
	return nil
}

// tryMakePaymentData attempts to generate valid payment data for a given member.
// It incorporates the 85% chance, date validation, and amount calculation.
func (g *PaymentGenerator) tryMakePaymentData(member MemberInfo) (Payment, bool) {
	// 85% chance of payment
	if g.rand.Float64() >= 0.85 {
		return Payment{}, false
	}

	// Generate payment date between member registration and now
	daysSinceRegistration := int(time.Since(member.RegistrationDate).Hours() / 24)
	if daysSinceRegistration <= 0 {
		return Payment{}, false
	}

	// Random day within the member's active period
	randomDays := g.rand.Intn(daysSinceRegistration)
	paymentDate := member.RegistrationDate.AddDate(0, 0, randomDays)

	// Skip if payment date is in the future (should not happen but safety check)
	if paymentDate.After(time.Now()) {
		return Payment{}, false
	}

	// Determine payment amount based on membership type
	var amount float64
	if member.MembershipType == "individual" {
		amount = GenerateRandomAmount(g.rand, 20, 40) // Individual membership: 20-40€
	} else {
		amount = GenerateRandomAmount(g.rand, 30, 60) // Family membership: 30-60€
	}

	// Random payment method
	paymentMethods := []string{"efectivo", "transferencia", "tarjeta"}
	paymentMethod := paymentMethods[g.rand.Intn(len(paymentMethods))]

	return Payment{
		MemberID:      member.ID,
		Amount:        amount,
		PaymentDate:   paymentDate,
		Status:        "paid",
		PaymentMethod: paymentMethod,
	}, true
}

// populateHistoricalPayments tries to generate payments based on member history.
// It appends to `currentPayments` until `maxPaymentsInBatch` is reached.
func (g *PaymentGenerator) populateHistoricalPayments(
	members []MemberInfo,
	maxPaymentsInBatch int,
	currentPayments []Payment,
) []Payment {
	// Keep track of member IDs already processed to avoid duplicates
	processedMembers := make(map[uint]struct{})
	for _, p := range currentPayments {
		processedMembers[p.MemberID] = struct{}{}
	}

	for _, member := range members {
		if len(currentPayments) >= maxPaymentsInBatch {
			break // Batch is full
		}

		if _, exists := processedMembers[member.ID]; exists {
			continue // Already processed this member
		}

		// Generate multiple payments for this member (simulating monthly/yearly payments)
		numPayments := g.rand.Intn(5) + 1 // 1-5 payments per member
		for i := 0; i < numPayments && len(currentPayments) < maxPaymentsInBatch; i++ {
			payment, ok := g.tryMakePaymentData(member)
			if ok {
				currentPayments = append(currentPayments, payment)
			}
		}
		processedMembers[member.ID] = struct{}{}
	}
	return currentPayments
}

// populateRandomFillPayments tries to generate more payments randomly if the batch isn't full.
// It appends to `currentPayments` until `maxPaymentsInBatch` is reached.
func (g *PaymentGenerator) populateRandomFillPayments(
	members []MemberInfo,
	maxPaymentsInBatch int,
	currentPayments []Payment,
) []Payment {
	maxAttempts := maxPaymentsInBatch * 5 // Safety break to avoid infinite loops
	attempts := 0

	for len(currentPayments) < maxPaymentsInBatch && attempts < maxAttempts {
		attempts++
		if len(members) == 0 {
			break
		}

		// Pick a random member
		member := members[g.rand.Intn(len(members))]

		payment, ok := g.tryMakePaymentData(member)
		if ok {
			currentPayments = append(currentPayments, payment)
		}
	}
	return currentPayments
}

// GetPaymentsByMember retrieves all payments for a given member
func (g *PaymentGenerator) GetPaymentsByMember(ctx context.Context, memberID uint) ([]Payment, error) {
	var payments []Payment
	query := `
		SELECT id, member_id, amount, payment_date, status, payment_method
		FROM payments
		WHERE member_id = $1
		ORDER BY payment_date DESC`

	err := g.db.SelectContext(ctx, &payments, query, memberID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Payment{}, nil // Return empty slice if no payments found
		}
		return nil, fmt.Errorf("failed to get payments for member %d: %w", memberID, err)
	}
	return payments, nil
}

// GetPaymentsByDateRange retrieves all payments within a date range
func (g *PaymentGenerator) GetPaymentsByDateRange(ctx context.Context, startDate, endDate time.Time) ([]Payment, error) {
	var payments []Payment
	query := `
		SELECT id, member_id, amount, payment_date, status, payment_method
		FROM payments
		WHERE payment_date >= $1 AND payment_date <= $2
		ORDER BY payment_date DESC`

	err := g.db.SelectContext(ctx, &payments, query, startDate, endDate)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []Payment{}, nil // Return empty slice if no payments found
		}
		return nil, fmt.Errorf("failed to get payments for date range: %w", err)
	}
	return payments, nil
}
