// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/javicabdev/asam-backend/internal/domain/models"
)

type AuthResponse struct {
	User         *models.User `json:"user"`
	AccessToken  string       `json:"accessToken"`
	RefreshToken string       `json:"refreshToken"`
	ExpiresAt    time.Time    `json:"expiresAt"`
}

type CashFlowBalance struct {
	TotalIncome    float64 `json:"totalIncome"`
	TotalExpenses  float64 `json:"totalExpenses"`
	CurrentBalance float64 `json:"currentBalance"`
}

type CashFlowStats struct {
	IncomeByCategory   []*CategoryAmount `json:"incomeByCategory"`
	ExpensesByCategory []*CategoryAmount `json:"expensesByCategory"`
	MonthlyTrend       []*MonthlyAmount  `json:"monthlyTrend"`
}

type CategoryAmount struct {
	Category models.OperationType `json:"category"`
	Amount   float64              `json:"amount"`
	Count    int                  `json:"count"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateCashFlowInput struct {
	MemberID      *string              `json:"member_id,omitempty"`
	OperationType models.OperationType `json:"operation_type"`
	Amount        float64              `json:"amount"`
	Date          time.Time            `json:"date"`
	Detail        string               `json:"detail"`
}

type CreateFamilyInput struct {
	NumeroSocio              string            `json:"numero_socio"`
	MiembroOrigenID          *string           `json:"miembro_origen_id,omitempty"`
	EsposoNombre             string            `json:"esposo_nombre"`
	EsposoApellidos          string            `json:"esposo_apellidos"`
	EsposoFechaNacimiento    *time.Time        `json:"esposo_fecha_nacimiento,omitempty"`
	EsposoDocumentoIdentidad *string           `json:"esposo_documento_identidad,omitempty"`
	EsposoCorreoElectronico  *string           `json:"esposo_correo_electronico,omitempty"`
	EsposaNombre             *string           `json:"esposa_nombre,omitempty"`
	EsposaApellidos          *string           `json:"esposa_apellidos,omitempty"`
	EsposaFechaNacimiento    *time.Time        `json:"esposa_fecha_nacimiento,omitempty"`
	EsposaDocumentoIdentidad *string           `json:"esposa_documento_identidad,omitempty"`
	EsposaCorreoElectronico  *string           `json:"esposa_correo_electronico,omitempty"`
	Familiares               []*FamiliarInput  `json:"familiares,omitempty"`
	Telefonos                []*TelephoneInput `json:"telefonos,omitempty"`
	Direccion                *string           `json:"direccion,omitempty"`
	CodigoPostal             *string           `json:"codigo_postal,omitempty"`
	Poblacion                *string           `json:"poblacion,omitempty"`
	Provincia                *string           `json:"provincia,omitempty"`
	Pais                     *string           `json:"pais,omitempty"`
}

type CreateMemberInput struct {
	NumeroSocio        string            `json:"numero_socio"`
	TipoMembresia      MembershipType    `json:"tipo_membresia"`
	Nombre             string            `json:"nombre"`
	Apellidos          string            `json:"apellidos"`
	CalleNumeroPiso    string            `json:"calle_numero_piso"`
	CodigoPostal       string            `json:"codigo_postal"`
	Poblacion          string            `json:"poblacion"`
	Provincia          *string           `json:"provincia,omitempty"`
	Pais               *string           `json:"pais,omitempty"`
	FechaAlta          *time.Time        `json:"fecha_alta,omitempty"`
	FechaNacimiento    *time.Time        `json:"fecha_nacimiento,omitempty"`
	DocumentoIdentidad *string           `json:"documento_identidad,omitempty"`
	CorreoElectronico  *string           `json:"correo_electronico,omitempty"`
	Profesion          *string           `json:"profesion,omitempty"`
	Nacionalidad       *string           `json:"nacionalidad,omitempty"`
	Observaciones      *string           `json:"observaciones,omitempty"`
	Telefonos          []*TelephoneInput `json:"telefonos,omitempty"`
}

type CreateUserInput struct {
	Username string   `json:"username"`
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
	MemberID *string  `json:"memberId,omitempty"`
}

type DashboardStats struct {
	TotalMembers            int                    `json:"totalMembers"`
	ActiveMembers           int                    `json:"activeMembers"`
	InactiveMembers         int                    `json:"inactiveMembers"`
	IndividualMembers       int                    `json:"individualMembers"`
	FamilyMembers           int                    `json:"familyMembers"`
	NewMembersThisMonth     int                    `json:"newMembersThisMonth"`
	NewMembersLastMonth     int                    `json:"newMembersLastMonth"`
	MemberGrowthPercentage  float64                `json:"memberGrowthPercentage"`
	TotalRevenue            float64                `json:"totalRevenue"`
	MonthlyRevenue          float64                `json:"monthlyRevenue"`
	PendingPayments         float64                `json:"pendingPayments"`
	AveragePayment          float64                `json:"averagePayment"`
	PaymentCompletionRate   float64                `json:"paymentCompletionRate"`
	RevenueGrowthPercentage float64                `json:"revenueGrowthPercentage"`
	CurrentBalance          float64                `json:"currentBalance"`
	MonthlyExpenses         float64                `json:"monthlyExpenses"`
	TotalTransactions       int                    `json:"totalTransactions"`
	RecentPaymentsCount     int                    `json:"recentPaymentsCount"`
	MembershipTrend         []*MembershipTrendData `json:"membershipTrend"`
	RevenueTrend            []*RevenueTrendData    `json:"revenueTrend"`
}

// Representa un deudor (socio o familia)
type Debtor struct {
	// ID del socio (si es deuda individual)
	MemberID *string `json:"memberId,omitempty"`
	// ID de la familia (si es deuda familiar)
	FamilyID *string `json:"familyId,omitempty"`
	// Tipo de deudor: "INDIVIDUAL" o "FAMILY"
	Type string `json:"type"`
	// Información del socio (si es individual)
	Member *DebtorMemberInfo `json:"member,omitempty"`
	// Información de la familia (si es familiar)
	Family *DebtorFamilyInfo `json:"family,omitempty"`
	// Lista de pagos pendientes
	PendingPayments []*PendingPayment `json:"pendingPayments"`
	// Importe total pendiente (suma de todos los pagos pendientes)
	TotalDebt float64 `json:"totalDebt"`
	// Días de atraso del pago más antiguo
	OldestDebtDays int `json:"oldestDebtDays"`
	// Fecha del pago pendiente más antiguo
	OldestDebtDate time.Time `json:"oldestDebtDate"`
	// Última fecha en que este socio/familia realizó un pago exitoso
	LastPaymentDate *time.Time `json:"lastPaymentDate,omitempty"`
	// Importe del último pago realizado
	LastPaymentAmount *float64 `json:"lastPaymentAmount,omitempty"`
}

// Información básica de la familia para el informe
type DebtorFamilyInfo struct {
	ID            string            `json:"id"`
	FamilyName    string            `json:"familyName"`
	PrimaryMember *DebtorMemberInfo `json:"primaryMember"`
	TotalMembers  int               `json:"totalMembers"`
}

// Información básica del socio para el informe
type DebtorMemberInfo struct {
	ID           string  `json:"id"`
	MemberNumber string  `json:"memberNumber"`
	FirstName    string  `json:"firstName"`
	LastName     string  `json:"lastName"`
	Email        *string `json:"email,omitempty"`
	Phone        *string `json:"phone,omitempty"`
	Status       string  `json:"status"`
}

// Parámetros de entrada para el informe de morosos
type DelinquentReportInput struct {
	// Fecha de corte para calcular la antigüedad de la deuda.
	// Si no se proporciona, se usa la fecha actual.
	CutoffDate *time.Time `json:"cutoffDate,omitempty"`
	// Importe mínimo de deuda para incluir en el informe.
	// Útil para filtrar deudas pequeñas.
	// Default: 0
	MinAmount *float64 `json:"minAmount,omitempty"`
	// Filtrar solo por socios individuales o familias
	// Valores: "INDIVIDUAL" | "FAMILY" | null (ambos)
	DebtorType *string `json:"debtorType,omitempty"`
	// Ordenamiento de resultados
	// Valores: "AMOUNT_DESC" | "AMOUNT_ASC" | "DAYS_DESC" | "DAYS_ASC" | "NAME_ASC"
	// Default: "DAYS_DESC" (más antiguas primero)
	SortBy *string `json:"sortBy,omitempty"`
	// Paginación
	Pagination *PaginationInput `json:"pagination,omitempty"`
}

// Respuesta del informe de morosos con paginación
type DelinquentReportResponse struct {
	// Lista de deudores (socios o familias) paginados
	Debtors []*Debtor `json:"debtors"`
	// Información de paginación
	PageInfo *PageInfo `json:"pageInfo"`
	// Estadísticas generales del informe (basadas en TODOS los deudores, no solo la página actual)
	Summary *DelinquentSummary `json:"summary"`
	// Fecha en que se generó el informe
	GeneratedAt time.Time `json:"generatedAt"`
}

// Resumen estadístico del informe
type DelinquentSummary struct {
	// Número total de deudores
	TotalDebtors int `json:"totalDebtors"`
	// Número de socios individuales con deuda
	IndividualDebtors int `json:"individualDebtors"`
	// Número de familias con deuda
	FamilyDebtors int `json:"familyDebtors"`
	// Importe total de todas las deudas
	TotalDebtAmount float64 `json:"totalDebtAmount"`
	// Promedio de días de atraso
	AverageDaysOverdue int `json:"averageDaysOverdue"`
	// Deuda promedio por deudor
	AverageDebtPerDebtor float64 `json:"averageDebtPerDebtor"`
}

type DocumentValidationResult struct {
	IsValid         bool    `json:"isValid"`
	NormalizedValue *string `json:"normalizedValue,omitempty"`
	ErrorMessage    *string `json:"errorMessage,omitempty"`
}

type FamiliarInput struct {
	Nombre            string            `json:"nombre"`
	Apellidos         string            `json:"apellidos"`
	FechaNacimiento   *time.Time        `json:"fecha_nacimiento,omitempty"`
	DniNie            *string           `json:"dni_nie,omitempty"`
	CorreoElectronico *string           `json:"correo_electronico,omitempty"`
	Parentesco        string            `json:"parentesco"`
	Telefonos         []*TelephoneInput `json:"telefonos,omitempty"`
}

type FamilyConnection struct {
	Nodes    []*models.Family `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type FamilyFilter struct {
	SearchTerm *string          `json:"search_term,omitempty"`
	Pagination *PaginationInput `json:"pagination,omitempty"`
	Sort       *SortInput       `json:"sort,omitempty"`
}

type GenerateAnnualFeesInput struct {
	Year           int     `json:"year"`
	BaseFeeAmount  float64 `json:"base_fee_amount"`
	FamilyFeeExtra float64 `json:"family_fee_extra"`
}

type GenerateAnnualFeesResponse struct {
	Year                int                        `json:"year"`
	MembershipFeeID     string                     `json:"membership_fee_id"`
	PaymentsGenerated   int                        `json:"payments_generated"`
	PaymentsExisting    int                        `json:"payments_existing"`
	TotalMembers        int                        `json:"total_members"`
	TotalExpectedAmount float64                    `json:"total_expected_amount"`
	Details             []*PaymentGenerationDetail `json:"details"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MemberConnection struct {
	Nodes    []*models.Member `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type MemberFilter struct {
	Estado        *MemberStatus    `json:"estado,omitempty"`
	TipoMembresia *MembershipType  `json:"tipo_membresia,omitempty"`
	SearchTerm    *string          `json:"search_term,omitempty"`
	Pagination    *PaginationInput `json:"pagination,omitempty"`
	Sort          *SortInput       `json:"sort,omitempty"`
}

type MembershipTrendData struct {
	Month        string `json:"month"`
	NewMembers   int    `json:"newMembers"`
	TotalMembers int    `json:"totalMembers"`
}

type MonthlyAmount struct {
	Month    string  `json:"month"`
	Income   float64 `json:"income"`
	Expenses float64 `json:"expenses"`
	Balance  float64 `json:"balance"`
}

type Mutation struct {
}

type MutationResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	TotalCount      int  `json:"totalCount"`
}

type PaginationInput struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type PaymentConnection struct {
	Nodes    []*models.Payment `json:"nodes"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type PaymentFilter struct {
	Status        *models.PaymentStatus `json:"status,omitempty"`
	PaymentMethod *string               `json:"payment_method,omitempty"`
	StartDate     *time.Time            `json:"start_date,omitempty"`
	EndDate       *time.Time            `json:"end_date,omitempty"`
	MinAmount     *float64              `json:"min_amount,omitempty"`
	MaxAmount     *float64              `json:"max_amount,omitempty"`
	MemberID      *string               `json:"member_id,omitempty"`
	Pagination    *PaginationInput      `json:"pagination,omitempty"`
	Sort          *SortInput            `json:"sort,omitempty"`
}

type PaymentGenerationDetail struct {
	MemberID     string  `json:"member_id"`
	MemberNumber string  `json:"member_number"`
	MemberName   string  `json:"member_name"`
	Amount       float64 `json:"amount"`
	WasCreated   bool    `json:"was_created"`
	Error        *string `json:"error,omitempty"`
}

type PaymentInput struct {
	MemberID      string  `json:"member_id"`
	Amount        float64 `json:"amount"`
	PaymentMethod string  `json:"payment_method"`
	Notes         *string `json:"notes,omitempty"`
}

// Información de un pago pendiente
type PendingPayment struct {
	ID          string    `json:"id"`
	Amount      float64   `json:"amount"`
	CreatedAt   time.Time `json:"createdAt"`
	DaysOverdue int       `json:"daysOverdue"`
	Notes       *string   `json:"notes,omitempty"`
}

type Query struct {
}

type RecentActivity struct {
	ID            string         `json:"id"`
	Type          ActivityType   `json:"type"`
	Description   string         `json:"description"`
	Timestamp     time.Time      `json:"timestamp"`
	RelatedMember *models.Member `json:"relatedMember,omitempty"`
	RelatedFamily *models.Family `json:"relatedFamily,omitempty"`
	Amount        *float64       `json:"amount,omitempty"`
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type RevenueTrendData struct {
	Month    string  `json:"month"`
	Revenue  float64 `json:"revenue"`
	Expenses float64 `json:"expenses"`
}

type SortInput struct {
	Field     string        `json:"field"`
	Direction SortDirection `json:"direction"`
}

type TelephoneInput struct {
	NumeroTelefono string `json:"numero_telefono"`
}

type TokenResponse struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type TransactionConnection struct {
	Nodes    []*models.CashFlow `json:"nodes"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type TransactionFilter struct {
	StartDate     *time.Time            `json:"start_date,omitempty"`
	EndDate       *time.Time            `json:"end_date,omitempty"`
	OperationType *models.OperationType `json:"operation_type,omitempty"`
	MemberID      *string               `json:"member_id,omitempty"`
	Category      *string               `json:"category,omitempty"`
	Pagination    *PaginationInput      `json:"pagination,omitempty"`
	Sort          *SortInput            `json:"sort,omitempty"`
}

type TransactionInput struct {
	MemberID      *string              `json:"member_id,omitempty"`
	OperationType models.OperationType `json:"operation_type"`
	Amount        float64              `json:"amount"`
	Date          time.Time            `json:"date"`
	Detail        string               `json:"detail"`
}

type UpdateCashFlowInput struct {
	OperationType *models.OperationType `json:"operation_type,omitempty"`
	Amount        *float64              `json:"amount,omitempty"`
	Date          *time.Time            `json:"date,omitempty"`
	Detail        *string               `json:"detail,omitempty"`
	MemberID      *string               `json:"member_id,omitempty"`
}

type UpdateFamilyInput struct {
	FamiliaID                string            `json:"familia_id"`
	EsposoNombre             *string           `json:"esposo_nombre,omitempty"`
	EsposoApellidos          *string           `json:"esposo_apellidos,omitempty"`
	EsposaNombre             *string           `json:"esposa_nombre,omitempty"`
	EsposaApellidos          *string           `json:"esposa_apellidos,omitempty"`
	EsposoDocumentoIdentidad *string           `json:"esposo_documento_identidad,omitempty"`
	EsposoCorreoElectronico  *string           `json:"esposo_correo_electronico,omitempty"`
	EsposaDocumentoIdentidad *string           `json:"esposa_documento_identidad,omitempty"`
	EsposaCorreoElectronico  *string           `json:"esposa_correo_electronico,omitempty"`
	Telefonos                []*TelephoneInput `json:"telefonos,omitempty"`
}

type UpdateMemberInput struct {
	MiembroID          string            `json:"miembro_id"`
	Nombre             *string           `json:"nombre,omitempty"`
	Apellidos          *string           `json:"apellidos,omitempty"`
	Nacionalidad       *string           `json:"nacionalidad,omitempty"`
	FechaNacimiento    *time.Time        `json:"fecha_nacimiento,omitempty"`
	CalleNumeroPiso    *string           `json:"calle_numero_piso,omitempty"`
	CodigoPostal       *string           `json:"codigo_postal,omitempty"`
	Poblacion          *string           `json:"poblacion,omitempty"`
	Provincia          *string           `json:"provincia,omitempty"`
	Pais               *string           `json:"pais,omitempty"`
	DocumentoIdentidad *string           `json:"documento_identidad,omitempty"`
	CorreoElectronico  *string           `json:"correo_electronico,omitempty"`
	Profesion          *string           `json:"profesion,omitempty"`
	Observaciones      *string           `json:"observaciones,omitempty"`
	Telefonos          []*TelephoneInput `json:"telefonos,omitempty"`
}

type UpdateUserInput struct {
	ID       string    `json:"id"`
	Username *string   `json:"username,omitempty"`
	Email    *string   `json:"email,omitempty"`
	Password *string   `json:"password,omitempty"`
	Role     *UserRole `json:"role,omitempty"`
	IsActive *bool     `json:"isActive,omitempty"`
	MemberID *string   `json:"memberId,omitempty"`
}

type UserConnection struct {
	Nodes    []*models.User `json:"nodes"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ActivityType string

const (
	ActivityTypeMemberRegistered    ActivityType = "MEMBER_REGISTERED"
	ActivityTypePaymentReceived     ActivityType = "PAYMENT_RECEIVED"
	ActivityTypeFamilyCreated       ActivityType = "FAMILY_CREATED"
	ActivityTypeMemberDeactivated   ActivityType = "MEMBER_DEACTIVATED"
	ActivityTypeTransactionRecorded ActivityType = "TRANSACTION_RECORDED"
)

var AllActivityType = []ActivityType{
	ActivityTypeMemberRegistered,
	ActivityTypePaymentReceived,
	ActivityTypeFamilyCreated,
	ActivityTypeMemberDeactivated,
	ActivityTypeTransactionRecorded,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeMemberRegistered, ActivityTypePaymentReceived, ActivityTypeFamilyCreated, ActivityTypeMemberDeactivated, ActivityTypeTransactionRecorded:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FamilySortField string

const (
	FamilySortFieldNumeroSocio  FamilySortField = "NUMERO_SOCIO"
	FamilySortFieldEsposoNombre FamilySortField = "ESPOSO_NOMBRE"
	FamilySortFieldEsposaNombre FamilySortField = "ESPOSA_NOMBRE"
)

var AllFamilySortField = []FamilySortField{
	FamilySortFieldNumeroSocio,
	FamilySortFieldEsposoNombre,
	FamilySortFieldEsposaNombre,
}

func (e FamilySortField) IsValid() bool {
	switch e {
	case FamilySortFieldNumeroSocio, FamilySortFieldEsposoNombre, FamilySortFieldEsposaNombre:
		return true
	}
	return false
}

func (e FamilySortField) String() string {
	return string(e)
}

func (e *FamilySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FamilySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FamilySortField", str)
	}
	return nil
}

func (e FamilySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FamilySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FamilySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberSortField string

const (
	MemberSortFieldNumeroSocio MemberSortField = "NUMERO_SOCIO"
	MemberSortFieldNombre      MemberSortField = "NOMBRE"
	MemberSortFieldApellidos   MemberSortField = "APELLIDOS"
	MemberSortFieldFechaAlta   MemberSortField = "FECHA_ALTA"
	MemberSortFieldEstado      MemberSortField = "ESTADO"
)

var AllMemberSortField = []MemberSortField{
	MemberSortFieldNumeroSocio,
	MemberSortFieldNombre,
	MemberSortFieldApellidos,
	MemberSortFieldFechaAlta,
	MemberSortFieldEstado,
}

func (e MemberSortField) IsValid() bool {
	switch e {
	case MemberSortFieldNumeroSocio, MemberSortFieldNombre, MemberSortFieldApellidos, MemberSortFieldFechaAlta, MemberSortFieldEstado:
		return true
	}
	return false
}

func (e MemberSortField) String() string {
	return string(e)
}

func (e *MemberSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberSortField", str)
	}
	return nil
}

func (e MemberSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberStatus string

const (
	MemberStatusActive   MemberStatus = "ACTIVE"
	MemberStatusInactive MemberStatus = "INACTIVE"
)

var AllMemberStatus = []MemberStatus{
	MemberStatusActive,
	MemberStatusInactive,
}

func (e MemberStatus) IsValid() bool {
	switch e {
	case MemberStatusActive, MemberStatusInactive:
		return true
	}
	return false
}

func (e MemberStatus) String() string {
	return string(e)
}

func (e *MemberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberStatus", str)
	}
	return nil
}

func (e MemberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MembershipType string

const (
	MembershipTypeIndividual MembershipType = "INDIVIDUAL"
	MembershipTypeFamily     MembershipType = "FAMILY"
)

var AllMembershipType = []MembershipType{
	MembershipTypeIndividual,
	MembershipTypeFamily,
}

func (e MembershipType) IsValid() bool {
	switch e {
	case MembershipTypeIndividual, MembershipTypeFamily:
		return true
	}
	return false
}

func (e MembershipType) String() string {
	return string(e)
}

func (e *MembershipType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MembershipType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MembershipType", str)
	}
	return nil
}

func (e MembershipType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MembershipType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MembershipType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionSortField string

const (
	TransactionSortFieldDate          TransactionSortField = "DATE"
	TransactionSortFieldAmount        TransactionSortField = "AMOUNT"
	TransactionSortFieldOperationType TransactionSortField = "OPERATION_TYPE"
)

var AllTransactionSortField = []TransactionSortField{
	TransactionSortFieldDate,
	TransactionSortFieldAmount,
	TransactionSortFieldOperationType,
}

func (e TransactionSortField) IsValid() bool {
	switch e {
	case TransactionSortFieldDate, TransactionSortFieldAmount, TransactionSortFieldOperationType:
		return true
	}
	return false
}

func (e TransactionSortField) String() string {
	return string(e)
}

func (e *TransactionSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionSortField", str)
	}
	return nil
}

func (e TransactionSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleUser,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleUser:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
