// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/javicabdev/asam-backend/internal/domain/models"
)

type AuthResponse struct {
	User         *models.User `json:"user"`
	AccessToken  string       `json:"accessToken"`
	RefreshToken string       `json:"refreshToken"`
	ExpiresAt    time.Time    `json:"expiresAt"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateFamilyInput struct {
	NumeroSocio              string     `json:"numero_socio"`
	MiembroOrigenID          *string    `json:"miembro_origen_id,omitempty"`
	EsposoNombre             string     `json:"esposo_nombre"`
	EsposoApellidos          string     `json:"esposo_apellidos"`
	EsposaNombre             string     `json:"esposa_nombre"`
	EsposaApellidos          string     `json:"esposa_apellidos"`
	EsposoFechaNacimiento    *time.Time `json:"esposo_fecha_nacimiento,omitempty"`
	EsposoDocumentoIdentidad *string    `json:"esposo_documento_identidad,omitempty"`
	EsposoCorreoElectronico  *string    `json:"esposo_correo_electronico,omitempty"`
	EsposaFechaNacimiento    *time.Time `json:"esposa_fecha_nacimiento,omitempty"`
	EsposaDocumentoIdentidad *string    `json:"esposa_documento_identidad,omitempty"`
	EsposaCorreoElectronico  *string    `json:"esposa_correo_electronico,omitempty"`
}

type CreateMemberInput struct {
	NumeroSocio        string         `json:"numero_socio"`
	TipoMembresia      MembershipType `json:"tipo_membresia"`
	Nombre             string         `json:"nombre"`
	Apellidos          string         `json:"apellidos"`
	CalleNumeroPiso    string         `json:"calle_numero_piso"`
	CodigoPostal       string         `json:"codigo_postal"`
	Poblacion          string         `json:"poblacion"`
	Provincia          *string        `json:"provincia,omitempty"`
	Pais               *string        `json:"pais,omitempty"`
	FechaNacimiento    *time.Time     `json:"fecha_nacimiento,omitempty"`
	DocumentoIdentidad *string        `json:"documento_identidad,omitempty"`
	CorreoElectronico  *string        `json:"correo_electronico,omitempty"`
	Profesion          *string        `json:"profesion,omitempty"`
	Nacionalidad       *string        `json:"nacionalidad,omitempty"`
	Observaciones      *string        `json:"observaciones,omitempty"`
}

type CreateUserInput struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
}

type DocumentValidationResult struct {
	IsValid         bool    `json:"isValid"`
	NormalizedValue *string `json:"normalizedValue,omitempty"`
	ErrorMessage    *string `json:"errorMessage,omitempty"`
}

type FamiliarInput struct {
	Nombre            string     `json:"nombre"`
	Apellidos         string     `json:"apellidos"`
	FechaNacimiento   *time.Time `json:"fecha_nacimiento,omitempty"`
	DniNie            *string    `json:"dni_nie,omitempty"`
	CorreoElectronico *string    `json:"correo_electronico,omitempty"`
	Parentesco        string     `json:"parentesco"`
}

type FamilyConnection struct {
	Nodes    []*models.Family `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type FamilyFilter struct {
	SearchTerm *string          `json:"search_term,omitempty"`
	Pagination *PaginationInput `json:"pagination,omitempty"`
	Sort       *SortInput       `json:"sort,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MemberConnection struct {
	Nodes    []*models.Member `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type MemberFilter struct {
	Estado        *MemberStatus    `json:"estado,omitempty"`
	TipoMembresia *MembershipType  `json:"tipo_membresia,omitempty"`
	SearchTerm    *string          `json:"search_term,omitempty"`
	Pagination    *PaginationInput `json:"pagination,omitempty"`
	Sort          *SortInput       `json:"sort,omitempty"`
}

type Mutation struct {
}

type MutationResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	TotalCount      int  `json:"totalCount"`
}

type PaginationInput struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type PaymentInput struct {
	MemberID      *string `json:"member_id,omitempty"`
	FamilyID      *string `json:"family_id,omitempty"`
	Amount        float64 `json:"amount"`
	PaymentMethod string  `json:"payment_method"`
	Notes         *string `json:"notes,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type SortInput struct {
	Field     string        `json:"field"`
	Direction SortDirection `json:"direction"`
}

type TokenResponse struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type TransactionConnection struct {
	Nodes    []*models.CashFlow `json:"nodes"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type TransactionFilter struct {
	StartDate     *time.Time            `json:"start_date,omitempty"`
	EndDate       *time.Time            `json:"end_date,omitempty"`
	OperationType *models.OperationType `json:"operation_type,omitempty"`
	Pagination    *PaginationInput      `json:"pagination,omitempty"`
	Sort          *SortInput            `json:"sort,omitempty"`
}

type TransactionInput struct {
	MemberID      *string              `json:"member_id,omitempty"`
	FamilyID      *string              `json:"family_id,omitempty"`
	OperationType models.OperationType `json:"operation_type"`
	Amount        float64              `json:"amount"`
	Date          time.Time            `json:"date"`
	Detail        string               `json:"detail"`
}

type UpdateFamilyInput struct {
	FamiliaID                string  `json:"familia_id"`
	EsposoNombre             *string `json:"esposo_nombre,omitempty"`
	EsposoApellidos          *string `json:"esposo_apellidos,omitempty"`
	EsposaNombre             *string `json:"esposa_nombre,omitempty"`
	EsposaApellidos          *string `json:"esposa_apellidos,omitempty"`
	EsposoDocumentoIdentidad *string `json:"esposo_documento_identidad,omitempty"`
	EsposoCorreoElectronico  *string `json:"esposo_correo_electronico,omitempty"`
	EsposaDocumentoIdentidad *string `json:"esposa_documento_identidad,omitempty"`
	EsposaCorreoElectronico  *string `json:"esposa_correo_electronico,omitempty"`
}

type UpdateMemberInput struct {
	MiembroID          string  `json:"miembro_id"`
	CalleNumeroPiso    *string `json:"calle_numero_piso,omitempty"`
	CodigoPostal       *string `json:"codigo_postal,omitempty"`
	Poblacion          *string `json:"poblacion,omitempty"`
	Provincia          *string `json:"provincia,omitempty"`
	Pais               *string `json:"pais,omitempty"`
	DocumentoIdentidad *string `json:"documento_identidad,omitempty"`
	CorreoElectronico  *string `json:"correo_electronico,omitempty"`
	Profesion          *string `json:"profesion,omitempty"`
	Observaciones      *string `json:"observaciones,omitempty"`
}

type UpdateUserInput struct {
	ID       string    `json:"id"`
	Username *string   `json:"username,omitempty"`
	Password *string   `json:"password,omitempty"`
	Role     *UserRole `json:"role,omitempty"`
	IsActive *bool     `json:"isActive,omitempty"`
}

type FamilySortField string

const (
	FamilySortFieldNumeroSocio  FamilySortField = "NUMERO_SOCIO"
	FamilySortFieldEsposoNombre FamilySortField = "ESPOSO_NOMBRE"
	FamilySortFieldEsposaNombre FamilySortField = "ESPOSA_NOMBRE"
)

var AllFamilySortField = []FamilySortField{
	FamilySortFieldNumeroSocio,
	FamilySortFieldEsposoNombre,
	FamilySortFieldEsposaNombre,
}

func (e FamilySortField) IsValid() bool {
	switch e {
	case FamilySortFieldNumeroSocio, FamilySortFieldEsposoNombre, FamilySortFieldEsposaNombre:
		return true
	}
	return false
}

func (e FamilySortField) String() string {
	return string(e)
}

func (e *FamilySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FamilySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FamilySortField", str)
	}
	return nil
}

func (e FamilySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FamilySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FamilySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberSortField string

const (
	MemberSortFieldNumeroSocio MemberSortField = "NUMERO_SOCIO"
	MemberSortFieldNombre      MemberSortField = "NOMBRE"
	MemberSortFieldApellidos   MemberSortField = "APELLIDOS"
	MemberSortFieldFechaAlta   MemberSortField = "FECHA_ALTA"
	MemberSortFieldEstado      MemberSortField = "ESTADO"
)

var AllMemberSortField = []MemberSortField{
	MemberSortFieldNumeroSocio,
	MemberSortFieldNombre,
	MemberSortFieldApellidos,
	MemberSortFieldFechaAlta,
	MemberSortFieldEstado,
}

func (e MemberSortField) IsValid() bool {
	switch e {
	case MemberSortFieldNumeroSocio, MemberSortFieldNombre, MemberSortFieldApellidos, MemberSortFieldFechaAlta, MemberSortFieldEstado:
		return true
	}
	return false
}

func (e MemberSortField) String() string {
	return string(e)
}

func (e *MemberSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberSortField", str)
	}
	return nil
}

func (e MemberSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberStatus string

const (
	MemberStatusActive   MemberStatus = "ACTIVE"
	MemberStatusInactive MemberStatus = "INACTIVE"
)

var AllMemberStatus = []MemberStatus{
	MemberStatusActive,
	MemberStatusInactive,
}

func (e MemberStatus) IsValid() bool {
	switch e {
	case MemberStatusActive, MemberStatusInactive:
		return true
	}
	return false
}

func (e MemberStatus) String() string {
	return string(e)
}

func (e *MemberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberStatus", str)
	}
	return nil
}

func (e MemberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MembershipType string

const (
	MembershipTypeIndividual MembershipType = "INDIVIDUAL"
	MembershipTypeFamily     MembershipType = "FAMILY"
)

var AllMembershipType = []MembershipType{
	MembershipTypeIndividual,
	MembershipTypeFamily,
}

func (e MembershipType) IsValid() bool {
	switch e {
	case MembershipTypeIndividual, MembershipTypeFamily:
		return true
	}
	return false
}

func (e MembershipType) String() string {
	return string(e)
}

func (e *MembershipType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MembershipType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MembershipType", str)
	}
	return nil
}

func (e MembershipType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MembershipType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MembershipType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionSortField string

const (
	TransactionSortFieldDate          TransactionSortField = "DATE"
	TransactionSortFieldAmount        TransactionSortField = "AMOUNT"
	TransactionSortFieldOperationType TransactionSortField = "OPERATION_TYPE"
)

var AllTransactionSortField = []TransactionSortField{
	TransactionSortFieldDate,
	TransactionSortFieldAmount,
	TransactionSortFieldOperationType,
}

func (e TransactionSortField) IsValid() bool {
	switch e {
	case TransactionSortFieldDate, TransactionSortFieldAmount, TransactionSortFieldOperationType:
		return true
	}
	return false
}

func (e TransactionSortField) String() string {
	return string(e)
}

func (e *TransactionSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionSortField", str)
	}
	return nil
}

func (e TransactionSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleUser,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleUser:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
